<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>4485911</PostId><Url>http://stackoverflow.com/questions/4485911</Url><Stack><Type>com_error</Type><Message>(-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147201021), None)</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\gen_py\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4.py</File><Line>2372</Line><Method>CmdLoadFromFile</Method></Frame></Stack></Post><Post><PostId>4972398</PostId><Url>http://stackoverflow.com/questions/4972398</Url><Stack><Type>com_error</Type><Message>(-2147024891, 'Access is denied.', None, None)</Message><Frame><File>C:\Python27\Lib\site-packages\Pythonwin\pywin\framework\scriptutils.py</File><Line>325</Line><Method>RunScript</Method></Frame><Frame><File>C:\Python27\sample\temp2.py</File><Line>8</Line><Method>module</Method></Frame><Frame><File>C:\Python27\sample\temp2.py</File><Line>5</Line><Method>get_printers</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\__init__.py</File><Line>72</Line><Method>GetObject</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\__init__.py</File><Line>87</Line><Method>Moniker</Method></Frame></Stack></Post><Post><PostId>5181456</PostId><Url>http://stackoverflow.com/questions/5181456</Url><Stack><Type>com_error</Type><Message>(-2147217375, 'OLE error 0x80041021', None, None)</Message><Frame><File>C:\Documents and Settings\xxx\Desktop\Python\Practice Code\System information\trial.py</File><Line>16</Line><Method>module</Method></Frame><Frame><File>C:\Documents and Settings\xxx\Desktop\Python\Practice Code\System information\trial.py</File><Line>5</Line><Method>sys_info</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\client\__init__.py</File><Line>72</Line><Method>GetObject</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\client\__init__.py</File><Line>87</Line><Method>Moniker</Method></Frame></Stack></Post><Post><PostId>8712806</PostId><Url>http://stackoverflow.com/questions/8712806</Url><Stack><Type>com_error</Type><Message>(-2147467262, 'No such interface supported', None, None)</Message><Frame><File>C:\python22\lib\threading.py</File><Line>414</Line><Method>__bootstrap</Method></Frame><Frame><File>C:\python22\lib\threading.py</File><Line>402</Line><Method>run</Method></Frame><Frame><File>testie.py</File><Line>42</Line><Method>printframes</Method></Frame><Frame><File>C:\python22\lib\site-packages\win32com\client\__init__.py</File><Line>455</Line><Method>__getattr__</Method></Frame><Frame><File>C:\python22\lib\site-packages\win32com\client\__init__.py</File><Line>446</Line><Method>_ApplyTypes_</Method></Frame></Stack></Post><Post><PostId>9325162</PostId><Url>http://stackoverflow.com/questions/9325162</Url><Stack><Type>com_error</Type><Message>(-2147221005, 'Invalid class string', None, None)</Message><Frame><File>C:\Users\SBYSMR10\Desktop\recipe-440493-1.py</File><Line>2</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\client\__init__.py</File><Line>95</Line><Method>Dispatch</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\client\dynamic.py</File><Line>108</Line><Method>_GetGoodDispatchAndUserName</Method></Frame><Frame><File>C:\Python26\lib\site-packages\win32com\client\dynamic.py</File><Line>85</Line><Method>_GetGoodDispatch</Method></Frame></Stack></Post><Post><PostId>9383307</PostId><Url>http://stackoverflow.com/questions/9383307</Url><Stack><Type>com_error</Type><Message>(-2147467263, 'Not implemented', None, None)</Message><Frame><File>C:\Documents and Settings\ablishen\workspace\HooverKeyCreator\src\HooverKeyCreator.py</File><Line>38</Line><Method>__pdf2Txt</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>505</Line><Method>__getattr__</Method></Frame></Stack></Post><Post><PostId>9982235</PostId><Url>http://stackoverflow.com/questions/9982235</Url><Stack><Type>com_error</Type><Message>(-2147024809, 'The parameter is incorrect.', None, None)</Message><Frame><File>interactive input</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11178464</PostId><Url>http://stackoverflow.com/questions/11178464</Url><Stack><Type>com_error</Type><Message>(-2147221005, 'Invalid class string', None, None)</Message><Frame><File>pyshell#3</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\__init__.py</File><Line>95</Line><Method>Dispatch</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>108</Line><Method>_GetGoodDispatchAndUserName</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>85</Line><Method>_GetGoodDispatch</Method></Frame></Stack></Post><Post><PostId>11623461</PostId><Url>http://stackoverflow.com/questions/11623461</Url><Stack><Type>com_error</Type><Message>(-2147352567, "Une exception s'est produite.", (4096, u'Microsoft Office Outlook', u'Index de la matrice en dehors des limites.', None, 0, -2147352567), None)</Message><Frame><File>D:\Documents and Settings\da7950\Mes documents\Dropbox\cheetahImporter\mapiImport.py</File><Line>42</Line><Method>module</Method></Frame><Frame><File>D:\Documents and Settings\da7950\Mes documents\Dropbox\cheetahImporter\mapiImport.py</File><Line>19</Line><Method>getContacts</Method></Frame><Frame><File>D:\Documents and Settings\da7950\Mes documents\Python27\lib\site-packages\win32com\gen_py\00062FFF-0000-0000-C000-000000000046x0x9x2\_Items.py</File><Line>122</Line><Method>__getitem__</Method></Frame></Stack></Post><Post><PostId>11909448</PostId><Url>http://stackoverflow.com/questions/11909448</Url><Stack><Type>com_error</Type><Message>(-2147217385, 'OLE error 0x80041017', None, None)</Message><Frame><File>pyshell#37</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\wmi.py</File><Line>1009</Line><Method>query</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\util.py</File><Line>84</Line><Method>next</Method></Frame></Stack></Post><Post><PostId>12039174</PostId><Url>http://stackoverflow.com/questions/12039174</Url><Stack><Type>com_error</Type><Message>(-2147221164, 'Class not registered', None, None)</Message><Frame><File>C:\Python27\Lib\site-packages\win32com\gen_py\APtest.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\__init__.py</File><Line>95</Line><Method>Dispatch</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>108</Line><Method>_GetGoodDispatchAndUserName</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>85</Line><Method>_GetGoodDispatch</Method></Frame></Stack></Post><Post><PostId>15274601</PostId><Url>http://stackoverflow.com/questions/15274601</Url><Stack><Type>com_error</Type><Message>(-2147352567, 'Exception occurred.', (0, u'Microsoft Word', u'This file could not be found.\r (C:\sectarianism.doc)', u'C:\Program Files\Microsoft Office\Office12\1033\WDMAIN11.CHM', 24654, -2146823114), None)</Message><Frame><File>C:\Users\User\Documents\python progs\misc\formatting for isn\formatting.py</File><Line>5</Line><Method>word.Documents.Open('C:\sectarianism.doc')</Method></Frame><Frame><File>C:\Python25\lib\site-packages\win32com\gen_py\00020905-0000-0000-C000-000000000046x0x8x4\Documents.py</File><Line>96</Line><Method>Open</Method></Frame></Stack></Post><Post><PostId>16946000</PostId><Url>http://stackoverflow.com/questions/16946000</Url><Stack><Type>com_error</Type><Message>(-2147221231, 'ClassFactory cannot supply requested class', None, None)</Message><Frame><File>pyshell#12</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\win32com\client\__init__.py</File><Line>95</Line><Method>Dispatch</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\win32com\client\dynamic.py</File><Line>108</Line><Method>_GetGoodDispatchAndUserName</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\win32com\client\dynamic.py</File><Line>85</Line><Method>_GetGoodDispatch</Method></Frame></Stack></Post><Post><PostId>17143510</PostId><Url>http://stackoverflow.com/questions/17143510</Url><Stack><Type>com_error</Type><Message>(-2146959355, 'Server execution failed', None, None)</Message><Frame><File>D:\report_polygon_count.py</File><Line>216</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\win32com\client\__init__.py</File><Line>113</Line><Method>DispatchEx</Method></Frame></Stack></Post><Post><PostId>18857395</PostId><Url>http://stackoverflow.com/questions/18857395</Url><Stack><Type>com_error</Type><Message>(-2147352567, 'Exception occurred.', (0, u'Microsoft Excel', u'SaveAs method of Workbook class failed', u'xlmain11.chm', 0, -2146827284), None)</Message><Frame><File>C:/scripts/excel/col_delete.py</File><Line>33</Line><Method>module</Method></Frame><Frame><File>C:/scripts/excel/col_delete.py</File><Line>24</Line><Method>run_excel</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\gen_py\00020813-0000-0000-C000-000000000046x0x1x7\_Workbook.py</File><Line>259</Line><Method>SaveAs</Method></Frame></Stack></Post><Post><PostId>20067712</PostId><Url>http://stackoverflow.com/questions/20067712</Url><Stack><Type>com_error</Type><Message>(-2147417851, 'The server threw an exception.', None, None</Message><Frame><File>C:\Users\jmp655972\Desktop\Handling_Analysis_Software\main.py</File><Line>120</Line><Method>module</Method></Frame><Frame><File>C:\Users\jmp655972\Desktop\Handling_Analysis_Software\main.py</File><Line>115</Line><Method>filescheck</Method></Frame><Frame><File>C:\Users\jmp655972\Desktop\Handling_Analysis_Software\main.py</File><Line>62</Line><Method>readFilesAndCopyData</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\gen_py\00020813-0000-0000-C000-000000000046x0x1x6.py</File><Line>34940</Line><Method>Open</Method></Frame></Stack></Post><Post><PostId>20132361</PostId><Url>http://stackoverflow.com/questions/20132361</Url><Stack><Type>com_error</Type><Message>(-2147467263, 'Not implemented', None, None)</Message><Frame><File>pyshell#31</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>511</Line><Method>__getattr__</Method></Frame></Stack></Post><Post><PostId>20259102</PostId><Url>http://stackoverflow.com/questions/20259102</Url><Stack><Type>com_error</Type><Message>(-2147352567, 'Exception occurred.', (0, u'S', u'Invalid Parameter', None, 0, -2146827284), None)</Message><Frame><File>C:\Users\jmp655972\Desktop\Handling_Analysis_Software\main.py</File><Line>186</Line><Method>addTrendLines()</Method></Frame><Frame><File>C:\Users\jmp655972\Desktop\Handling_Analysis_Software\main.py</File><Line>160</Line><Method>addTrendLines</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\gen_py\00020813-0000-0000-C000-000000000046x0x1x6.py</File><Line>38555</Line><Method>SeriesCollection</Method></Frame></Stack></Post><Post><PostId>21316009</PostId><Url>http://stackoverflow.com/questions/21316009</Url><Stack><Type>com_error</Type><Message>(-2147221164, 'Class not registered', None, None)</Message><Frame><File>D:\MyWorkSpace\testProgs\ATL_COM\WPF\MyWpfApp\MyWin32App\Python\MyPythonClient.py</File><Line>15</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\__init__.py</File><Line>95</Line><Method>Dispatch</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>114</Line><Method>_GetGoodDispatchAndUserName</Method></Frame><Frame><File>C:\Python27\lib\site-packages\win32com\client\dynamic.py</File><Line>91</Line><Method>_GetGoodDispatch</Method></Frame></Stack></Post><Post><PostId>23514788</PostId><Url>http://stackoverflow.com/questions/23514788</Url><Stack><Type>com_error</Type><Message>(-2147467259, 'Unspecified error', None, None)</Message><Frame><File>C:\Python27_64\Lib\site-packages\win32comext\mapi\demos\mapisend.py</File><Line>85</Line><Method>module</Method></Frame><Frame><File>C:\Python27_64\Lib\site-packages\win32comext\mapi\demos\mapisend.py</File><Line>23</Line><Method>SendEMAPIMail</Method></Frame></Stack></Post></Posts>