<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>21073101</PostId><Url>http://stackoverflow.com/questions/21073101</Url><Stack><Type>ConnectionResetError</Type><Message>[Errno 104] Connection reset by peer</Message><Frame><File>/home/philipp/.config/sublime-text-3/Packages/Ruby Debugger/debugge/ruby_imp/ruby_debugger_connector.py</File><Line>102</Line><Method>reader_thread</Method></Frame></Stack></Post><Post><PostId>21265645</PostId><Url>http://stackoverflow.com/questions/21265645</Url><Stack><Type>ConnectionResetError</Type><Message>[Errno 104] Connection reset by peer</Message><Frame><File>StockTrackerJSON.py</File><Line>1481</Line><Method>module</Method></Frame><Frame><File>StockTrackerJSON.py</File><Line>1140</Line><Method>__init__</Method></Frame><Frame><File>StockTrackerJSON.py</File><Line>659</Line><Method>htmlTableRowOutput</Method></Frame><Frame><File>StockTrackerJSON.py</File><Line>1006</Line><Method>resultsIfInvestedInSP500</Method></Frame><Frame><File>StockTrackerJSON.py</File><Line>456</Line><Method>getSharePrice</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>156</Line><Method>urlopen</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>469</Line><Method>open</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>487</Line><Method>_open</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>447</Line><Method>_call_chain</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>1268</Line><Method>http_open</Method></Frame><Frame><File>/usr/lib/python3.3/urllib/request.py</File><Line>1253</Line><Method>do_open</Method></Frame><Frame><File>/usr/lib/python3.3/http/client.py</File><Line>1147</Line><Method>getresponse</Method></Frame><Frame><File>/usr/lib/python3.3/http/client.py</File><Line>358</Line><Method>begin</Method></Frame><Frame><File>/usr/lib/python3.3/http/client.py</File><Line>320</Line><Method>_read_status</Method></Frame><Frame><File>/usr/lib/python3.3/socket.py</File><Line>297</Line><Method>readinto</Method></Frame></Stack></Post><Post><PostId>24145618</PostId><Url>http://stackoverflow.com/questions/24145618</Url><Stack><Type>ConnectionResetError</Type><Message>[WinError 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>C:\Python34\lib\tkinter\__init__.py</File><Line>1487</Line><Method>__call__</Method></Frame><Frame><File>C:\Users\kylec\Desktop\Data Motion\Mail Server Finder\mailserverfinder.py</File><Line>58</Line><Method>getServers</Method></Frame><Frame><File>C:\Python34\lib\telnetlib.py</File><Line>317</Line><Method>read_until</Method></Frame><Frame><File>C:\Python34\lib\telnetlib.py</File><Line>526</Line><Method>fill_rawq</Method></Frame></Stack></Post><Post><PostId>25326616</PostId><Url>http://stackoverflow.com/questions/25326616</Url><Stack><Type>ConnectionResetError</Type><Message>[WinError 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>313</Line><Method>_make_request</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>480</Line><Method>urlopen</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>315</Line><Method>_make_request</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>1147</Line><Method>getresponse</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>358</Line><Method>begin</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>320</Line><Method>_read_status</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\socket.py</File><Line>297</Line><Method>readinto</Method></Frame></Stack></Post><Post><PostId>25326616</PostId><Url>http://stackoverflow.com/questions/25326616</Url><Stack><Type>ConnectionResetError</Type><Message>[WinError 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>313</Line><Method>_make_request</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>480</Line><Method>urlopen</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py</File><Line>315</Line><Method>_make_request</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>1147</Line><Method>getresponse</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>358</Line><Method>begin</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\http\client.py</File><Line>320</Line><Method>_read_status</Method></Frame><Frame><File>C:\Kivy180\Python33\lib\socket.py</File><Line>297</Line><Method>readinto</Method></Frame></Stack></Post><Post><PostId>25746719</PostId><Url>http://stackoverflow.com/questions/25746719</Url><Stack><Type>ConnectionResetError</Type><Message>[WinError 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>C:\Python34\lib\site-packages\requests-2.3.0-py3.4.egg\requests\packages\urllib3\connectionpool.py</File><Line>485</Line><Method>urlopen</Method></Frame><Frame><File>C:\Python34\lib\site-packages\requests-2.3.0-py3.4.egg\requests\packages\urllib3\connectionpool.py</File><Line>283</Line><Method>_make_request</Method></Frame><Frame><File>C:\Python34\lib\http\client.py</File><Line>1066</Line><Method>request</Method></Frame><Frame><File>C:\Python34\lib\http\client.py</File><Line>1104</Line><Method>_send_request</Method></Frame><Frame><File>C:\Python34\lib\http\client.py</File><Line>1062</Line><Method>endheaders</Method></Frame><Frame><File>C:\Python34\lib\http\client.py</File><Line>907</Line><Method>_send_output</Method></Frame><Frame><File>C:\Python34\lib\http\client.py</File><Line>842</Line><Method>send</Method></Frame><Frame><File>C:\Python34\lib\site-packages\requests-2.3.0-py3.4.egg\requests\packages\urllib3\connection.py</File><Line>181</Line><Method>connect</Method></Frame><Frame><File>C:\Python34\lib\site-packages\requests-2.3.0-py3.4.egg\requests\packages\urllib3\util.py</File><Line>639</Line><Method>ssl_wrap_socket</Method></Frame><Frame><File>C:\Python34\lib\ssl.py</File><Line>344</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Python34\lib\ssl.py</File><Line>540</Line><Method>__init__</Method></Frame><Frame><File>C:\Python34\lib\ssl.py</File><Line>767</Line><Method>do_handshake</Method></Frame></Stack></Post></Posts>