<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>1637561</PostId><Url>http://stackoverflow.com/questions/1637561</Url><Stack><Type>DoesNotExist</Type><Message>UserProfile matching query does not exist.</Message><Frame><File>/Users/michael/django/trunk/django/contrib/auth/tests/views.py</File><Line>156</Line><Method>test_password_change_fails_with_invalid_old_password</Method></Frame><Frame><File>/Users/michael/django/trunk/django/test/client.py</File><Line>318</Line><Method>post</Method></Frame><Frame><File>/Users/michael/django/trunk/django/core/handlers/base.py</File><Line>87</Line><Method>get_response</Method></Frame><Frame><File>/Users/michael/Documents/workspace/drchrono/drchrono_middleware/drchrono.py</File><Line>31</Line><Method>process_view</Method></Frame><Frame><File>/Users/michael/django/trunk/django/contrib/auth/models.py</File><Line>285</Line><Method>get_profile</Method></Frame><Frame><File>/Users/michael/django/trunk/django/db/models/manager.py</File><Line>119</Line><Method>get</Method></Frame><Frame><File>/Users/michael/django/trunk/django/db/models/query.py</File><Line>298</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>2908795</PostId><Url>http://stackoverflow.com/questions/2908795</Url><Stack><Type>DoesNotExist</Type><Message>User matching query does not exist.</Message><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/commands/loaddata.py</File><Line>169</Line><Method>handle</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/serializers/base.py</File><Line>165</Line><Method>save</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/models/base.py</File><Line>543</Line><Method>save_base</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/dispatch/dispatcher.py</File><Line>162</Line><Method>send</Method></Frame><Frame><File>/Users/Bryan/work/CNPROG/forum/models.py</File><Line>656</Line><Method>record_ask_event</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/models/fields/related.py</File><Line>302</Line><Method>__get__</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/models/query.py</File><Line>341</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>4888676</PostId><Url>http://stackoverflow.com/questions/4888676</Url><Stack><Type>DoesNotExist</Type><Message>Product matching query does not exist.</Message><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/core/management/commands/loaddata.py</File><Line>174</Line><Method>handle</Method></Frame><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/core/serializers/base.py</File><Line>165</Line><Method>save</Method></Frame><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/db/models/base.py</File><Line>570</Line><Method>save_base</Method></Frame><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/dispatch/dispatcher.py</File><Line>172</Line><Method>send</Method></Frame><Frame><File>/Users/cp/bidsite/apps/mainsite/models.py</File><Line>257</Line><Method>update_auction_details</Method></Frame><Frame><File>/Users/cp/bidsite/apps/mainsite/models.py</File><Line>1110</Line><Method>as_json</Method></Frame><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/db/models/fields/related.py</File><Line>315</Line><Method>__get__</Method></Frame><Frame><File>/Users/cp/bidsite/.ve/lib/python2.6/site-packages/django/db/models/query.py</File><Line>349</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>5544729</PostId><Url>http://stackoverflow.com/questions/5544729</Url><Stack><Type>DoesNotExist</Type><Message>Site matching query does not exist.</Message><Frame><File>/var/lib/django/bsdata/shoppingcart/tests.py</File><Line>50</Line><Method>test_infopage</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/test/client.py</File><Line>313</Line><Method>post</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/core/handlers/base.py</File><Line>92</Line><Method>get_response</Method></Frame><Frame><File>/var/lib/django/.../views.py</File><Line>22</Line><Method>start</Method></Frame><Frame><File>/var/lib/django/...views.py</File><Line>238</Line><Method>getCostInfo</Method></Frame><Frame><File>/var/lib/django/.../managers.py</File><Line>16</Line><Method>getLoadedDict</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/db/models/manager.py</File><Line>120</Line><Method>get</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/db/models/query.py</File><Line>305</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>5733129</PostId><Url>http://stackoverflow.com/questions/5733129</Url><Stack><Type>DoesNotExist</Type><Message>Team matching query does not exist.</Message><Frame><File>/usr/lib/pymodules/python2.6/nose/case.py</File><Line>183</Line><Method>runTest</Method></Frame><Frame><File>/home/charlie/code/tempsite/../tempsite/tmg/tests.py</File><Line>8</Line><Method>testTeamGetTesters_test</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/db/models/manager.py</File><Line>132</Line><Method>get</Method></Frame><Frame><File>/usr/lib/pymodules/python2.6/django/db/models/query.py</File><Line>341</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>5886534</PostId><Url>http://stackoverflow.com/questions/5886534</Url><Stack><Type>DoesNotExist</Type><Message>User matching query does not exist.</Message><Frame><File>/Users/Bryan/work/osqa/forum/tests/tests_building_stickyness.py</File><Line>18</Line><Method>testAdminCanFavorite</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/Django-1.3-py2.7.egg/django/db/models/manager.py</File><Line>132</Line><Method>get</Method></Frame><Frame><File>/Users/Bryan/work/osqa/forum/models/base.py</File><Line>64</Line><Method>get</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/Django-1.3-py2.7.egg/django/db/models/query.py</File><Line>349</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>6080024</PostId><Url>http://stackoverflow.com/questions/6080024</Url><Stack><Type>DoesNotExist</Type><Message>Post matching query does not exist.</Message><Frame><File>/home/user/opt/local/django/core/handlers/base.py</File><Line>100</Line><Method>get_response</Method></Frame><Frame><File>/web/blog/views.py</File><Line>33</Line><Method>post</Method></Frame><Frame><File>/home/user/local/django/db/models/manager.py</File><Line>132</Line><Method>get</Method></Frame><Frame><File>/home/user/opt/local/django/db/models/query.py</File><Line>347</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>8447426</PostId><Url>http://stackoverflow.com/questions/8447426</Url><Stack><Type>DoesNotExist</Type><Message>User matching query does not exist.</Message><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/core/management/commands/loaddata.py</File><Line>174</Line><Method>handle</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/core/serializers/base.py</File><Line>165</Line><Method>save</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/db/models/base.py</File><Line>570</Line><Method>save_base</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/dispatch/dispatcher.py</File><Line>172</Line><Method>send</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/python/lib/python2.6/site-packages/djangobb_for_dcif/signals.py</File><Line>18</Line><Method>post_saved</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/db/models/fields/related.py</File><Line>315</Line><Method>__get__</Method></Frame><Frame><File>/Applications/djangostack-1.3-0/apps/django/lib/python2.6/site-packages/django/db/models/query.py</File><Line>349</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>9898545</PostId><Url>http://stackoverflow.com/questions/9898545</Url><Stack><Type>DoesNotExist</Type><Message>User matching query does not exist</Message><Frame><File>/var/lib/graphyte-webclient/webclient/apps/codebundles/tests.py</File><Line>10</Line><Method>setUp</Method></Frame><Frame><File>/var/lib/graphyte-webclient/graphyte-webenv/lib/python2.6/site-packages/django/db/models/manager.py</File><Line>132</Line><Method>get</Method></Frame><Frame><File>/var/lib/graphyte-webclient/graphyte-webenv/lib/python2.6/site-packages/django/db/models/query.py</File><Line>341</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>12168941</PostId><Url>http://stackoverflow.com/questions/12168941</Url><Stack><Type>DoesNotExist</Type><Message>ContentType matching query does not exist.</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py</File><Line>111</Line><Method>get_response</Method></Frame><Frame><File>/home/ubuntu/src/cbframe/commentableobjects/views/commentableobject_list.py</File><Line>142</Line><Method>commentablobject_list</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py</File><Line>20</Line><Method>render_to_response</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader.py</File><Line>176</Line><Method>render_to_string</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>140</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>823</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>123</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>823</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>62</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>823</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py</File><Line>281</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>823</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>155</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>137</Line><Method>render_template</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>140</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>823</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py</File><Line>185</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>1139</Line><Method>render</Method></Frame><Frame><File>/home/ubuntu/src/cbframe/commentableobjects/templatetags/url_target_blank.py</File><Line>27</Line><Method>is_contest</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py</File><Line>350</Line><Method>__get__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/query.py</File><Line>366</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>16545764</PostId><Url>http://stackoverflow.com/questions/16545764</Url><Stack><Type>DoesNotExist</Type><Message>Site matching query does not exist.</Message><Frame><File>C:\python27\lib\site-packages\django\core\handlers\base.py</File><Line>111</Line><Method>get_response</Method></Frame><Frame><File>c:\inetpub\wwwroot\osqa\[mysite.com]\forum\views\readers.py</File><Line>73</Line><Method>feed</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\contrib\syndication\views.py</File><Line>37</Line><Method>__call__</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\contrib\syndication\views.py</File><Line>97</Line><Method>get_feed</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\contrib\sites\models.py</File><Line>92</Line><Method>get_current_site</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\contrib\sites\models.py</File><Line>25</Line><Method>get_current</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\db\models\manager.py</File><Line>132</Line><Method>get</Method></Frame><Frame><File>C:\python27\lib\site-packages\django\db\models\query.py</File><Line>349</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>17612419</PostId><Url>http://stackoverflow.com/questions/17612419</Url><Stack><Type>DoesNotExist</Type><Message>Contact matching query does not exist. Lookup parameters were {'mobile': '07000000000'}</Message><Frame><File>/Users/user/Documents/workspace/example/sms/tests/test_sms_simulation.py</File><Line>18</Line><Method>test_get_contact</Method></Frame><Frame><File>/Users/user/Documents/workspace/example/django-env/lib/python2.7/site-packages/django/db/models/manager.py</File><Line>143</Line><Method>get</Method></Frame><Frame><File>/Users/user/Documents/workspace/example/django-env/lib/python2.7/site-packages/django/db/models/query.py</File><Line>389</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>17813919</PostId><Url>http://stackoverflow.com/questions/17813919</Url><Stack><Type>DoesNotExist</Type><Message>Comment matching query does not exist</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py</File><Line>111</Line><Method>get_response</Method></Frame><Frame><File>home/ubuntu/server/opineer/comments/views.py</File><Line>103</Line><Method>comment_expand</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py</File><Line>131</Line><Method>get</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/query.py</File><Line>366</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>19896443</PostId><Url>http://stackoverflow.com/questions/19896443</Url><Stack><Type>DoesNotExist</Type><Message>Permission matching query does not exist.</Message><Frame><File>/usr/local/lib/python2.7/site-packages/django/contrib/auth/tests/context_processors.py</File><Line>108</Line><Method>test_perms_attrs</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/django/db/models/manager.py</File><Line>143</Line><Method>get</Method></Frame><Frame><File>'/usr/local/lib/python2.7/site-packages/django/db/models/query.py</File><Line>404</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>23991502</PostId><Url>http://stackoverflow.com/questions/23991502</Url><Stack><Type>DoesNotExist</Type><Message>AssignmentKit matching query does not exist.</Message><Frame><File>/opt/2.0/site/toolbox/tests.py</File><Line>20</Line><Method>test_update_quiz</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/django/db/models/manager.py</File><Line>131</Line><Method>get</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/django/db/models/query.py</File><Line>366</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>24794696</PostId><Url>http://stackoverflow.com/questions/24794696</Url><Stack><Type>DoesNotExist</Type><Message>Cage has no zookeeper.</Message><Frame><File>../zoo/models.py</File><Line>185</Line><Method>on_cage_init</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py</File><Line>324</Line><Method>__get__</Method></Frame></Stack></Post></Posts>