<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>16192493</PostId><Url>http://stackoverflow.com/questions/16192493</Url><Stack><Type>except_osv</Type><Message>(u'Aeroo Reports: Error while generating the report "Prueba".', XMLSyntaxError(u"Start tag expected, '</Message><Frame><File>/home/jorge-hernan/openerp/dev/server/openerp/service/web_services.py</File><Line>727</Line><Method>go</Method></Frame><Frame><File>/home/jorge-hernan/openerp/dev/server/openerp/addons/report_aeroo/report_aeroo.py</File><Line>713</Line><Method>create</Method></Frame><Frame><File>/home/jorge-hernan/openerp/dev/server/openerp/addons/report_aeroo/report_aeroo.py</File><Line>656</Line><Method>create_source_odt</Method></Frame><Frame><File>/home/jorge-hernan/openerp/dev/server/openerp/addons/report_aeroo/report_aeroo.py</File><Line>497</Line><Method>create_single_pdf</Method></Frame><Frame><File>/home/jorge-hernan/openerp/dev/server/openerp/addons/report_aeroo/report_aeroo.py</File><Line>448</Line><Method>create_aeroo_report</Method></Frame></Stack></Post><Post><PostId>19290700</PostId><Url>http://stackoverflow.com/questions/19290700</Url><Stack><Type>except_osv</Type><Message>(u'Connection Test Failed!', u'Hier sehen Sie, was wir an Stelle dessen bekommen haben:\n 110\nDie Wartezeit f\xfcr die Verbindung ist abgelaufen')</Message><Frame><File>/usr/lib/pymodules/python2.7/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/service/web_services.py</File><Line>626</Line><Method>dispatch</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>188</Line><Method>execute_kw</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>131</Line><Method>wrapper</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>197</Line><Method>execute</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>185</Line><Method>execute_cr</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_mail_server.py</File><Line>215</Line><Method>test_smtp_connection</Method></Frame></Stack></Post><Post><PostId>19750986</PostId><Url>http://stackoverflow.com/questions/19750986</Url><Stack><Type>except_osv</Type><Message>('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')</Message><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>126</Line><Method>_check_render_view</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2239</Line><Method>fields_view_get</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2197</Line><Method>apply_view_inheritance</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2181</Line><Method>apply_inheritance_specs</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2074</Line><Method>raise_view_error</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>847</Line><Method>parse</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>814</Line><Method>_tag_record</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py</File><Line>967</Line><Method>_update</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>103</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>4478</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>1548</Line><Method>_validate</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/service/web_services.py</File><Line>626</Line><Method>dispatch</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>188</Line><Method>execute_kw</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>144</Line><Method>wrapper</Method></Frame></Stack></Post><Post><PostId>19750986</PostId><Url>http://stackoverflow.com/questions/19750986</Url><Stack><Type>except_osv</Type><Message>('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')</Message><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>126</Line><Method>_check_render_view</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2239</Line><Method>fields_view_get</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2197</Line><Method>apply_view_inheritance</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2181</Line><Method>apply_inheritance_specs</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2074</Line><Method>raise_view_error</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>847</Line><Method>parse</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>814</Line><Method>_tag_record</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py</File><Line>967</Line><Method>_update</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>103</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>4478</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>1548</Line><Method>_validate</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/service/web_services.py</File><Line>626</Line><Method>dispatch</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>188</Line><Method>execute_kw</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>144</Line><Method>wrapper</Method></Frame></Stack></Post><Post><PostId>19750986</PostId><Url>http://stackoverflow.com/questions/19750986</Url><Stack><Type>except_osv</Type><Message>('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')</Message><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>126</Line><Method>_check_render_view</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2239</Line><Method>fields_view_get</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2197</Line><Method>apply_view_inheritance</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2181</Line><Method>apply_inheritance_specs</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>2074</Line><Method>raise_view_error</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>847</Line><Method>parse</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/tools/convert.py</File><Line>814</Line><Method>_tag_record</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py</File><Line>967</Line><Method>_update</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_ui_view.py</File><Line>103</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>4478</Line><Method>create</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/orm.py</File><Line>1548</Line><Method>_validate</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/service/web_services.py</File><Line>626</Line><Method>dispatch</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>188</Line><Method>execute_kw</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>144</Line><Method>wrapper</Method></Frame></Stack></Post><Post><PostId>23913719</PostId><Url>http://stackoverflow.com/questions/23913719</Url><Stack><Type>except_osv</Type><Message>(u'8\nExec format error', (</Message><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>712</Line><Method>go</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>340</Line><Method>create</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/report/report_sxw.py</File><Line>513</Line><Method>create_source_pdf</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>314</Line><Method>create_single_pdf</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>165</Line><Method>generate_pdf</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>493</Line><Method>call</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>679</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>1249</Line><Method>_execute_child</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>654</Line><Method>dispatch</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>760</Line><Method>exp_report_get</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>738</Line><Method>_check_report</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/netsvc.py</File><Line>71</Line><Method>abort_response</Method></Frame></Stack></Post><Post><PostId>23913719</PostId><Url>http://stackoverflow.com/questions/23913719</Url><Stack><Type>except_osv</Type><Message>(u'8\nExec format error', (</Message><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>712</Line><Method>go</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>340</Line><Method>create</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/report/report_sxw.py</File><Line>513</Line><Method>create_source_pdf</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>314</Line><Method>create_single_pdf</Method></Frame><Frame><File>/opt/openerp-report/addons/report_webkit/webkit_report.py</File><Line>165</Line><Method>generate_pdf</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>493</Line><Method>call</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>679</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/subprocess.py</File><Line>1249</Line><Method>_execute_child</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>654</Line><Method>dispatch</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>760</Line><Method>exp_report_get</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/service/web_services.py</File><Line>738</Line><Method>_check_report</Method></Frame><Frame><File>/opt/openerp-report/server/openerp/netsvc.py</File><Line>71</Line><Method>abort_response</Method></Frame></Stack></Post></Posts>