<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13256777</PostId><Url>http://stackoverflow.com/questions/13256777</Url><Stack><Type>MyException</Type><Message>something bad with field \u4443</Message><Frame><File>C:\Python27\lib\bdb.py</File><Line>387</Line><Method>run</Method></Frame><Frame><File>C:\Users\ghis3080\r.py</File><Line>25</Line><Method>module</Method></Frame></Stack></Post></Posts>