<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>8989690</PostId><Url>http://stackoverflow.com/questions/8989690</Url><Stack><Type>OverQuotaError</Type><Message>The API call logservice.Read() required more quota than is available.</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py</File><Line>701</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/xxx/3.356325783019142341/xxx.py</File><Line>355</Line><Method>get</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/logservice/logservice.py</File><Line>414</Line><Method>__iter__</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/logservice/logservice.py</File><Line>427</Line><Method>_advance</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>94</Line><Method>MakeSyncCall</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>308</Line><Method>MakeSyncCall</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>10340717</PostId><Url>http://stackoverflow.com/questions/10340717</Url><Stack><Type>OverQuotaError</Type><Message>The API call file.Open() required more quota than is available.</Message><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1511</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1505</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1253</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1077</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>547</Line><Method>dispatch</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>545</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/base_handler.py</File><Line>68</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/handlers.py</File><Line>168</Line><Method>handle</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/mapreduce_pipeline.py</File><Line>109</Line><Method>__iter__</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/input_readers.py</File><Line>1615</Line><Method>__iter__</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/records.py</File><Line>335</Line><Method>read</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/records.py</File><Line>292</Line><Method>__try_read_record</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>569</Line><Method>read</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>436</Line><Method>open</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>269</Line><Method>__init__</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>393</Line><Method>_open</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>397</Line><Method>_make_rpc_call_with_retry</Method></Frame><Frame><File>/base/data/home/apps/s~utest-appgraph/69.358421800203055451/mapreduce/lib/files/file.py</File><Line>243</Line><Method>_make_call</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>558</Line><Method>check_success</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post></Posts>