<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>18939474</PostId><Url>http://stackoverflow.com/questions/18939474</Url><Stack><Type>TooManyConnections</Type><Message>50 connections are already equal to the max: 50</Message><Frame><File>/home/ubuntu/envs/myproj/local/lib/python2.7/site-packages/tornado/web.py</File><Line>1115</Line><Method>_stack_context_handle_exception</Method></Frame><Frame><File>/home/ubuntu/envs/myproj/local/lib/python2.7/site-packages/tornado/web.py</File><Line>1298</Line><Method>wrapper</Method></Frame><Frame><File>bench.py</File><Line>29</Line><Method>get</Method></Frame><Frame><File>/home/ubuntu/envs/myproj/local/lib/python2.7/site-packages/asyncmongo/cursor.py</File><Line>380</Line><Method>find</Method></Frame><Frame><File>/home/ubuntu/envs/myproj/local/lib/python2.7/site-packages/asyncmongo/pool.py</File><Line>116</Line><Method>connection</Method></Frame></Stack></Post></Posts>