<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>2835908</PostId><Url>http://stackoverflow.com/questions/2835908</Url><Stack><Type>Unauthorized</Type><Message>Unauthorized - Server responded with: 401,</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>511</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/mustrun2sun/1.341947133742569880/main.py</File><Line>170</Line><Method>get</Method></Frame><Frame><File>/base/data/home/apps/mustrun2sun/1.341947133742569880/gdata/docs/client.py</File><Line>141</Line><Method>get_doclist</Method></Frame><Frame><File>/base/data/home/apps/mustrun2sun/1.341947133742569880/gdata/client.py</File><Line>635</Line><Method>get_feed</Method></Frame><Frame><File>/base/data/home/apps/mustrun2sun/1.341947133742569880/gdata/client.py</File><Line>308</Line><Method>request</Method></Frame></Stack></Post><Post><PostId>19740109</PostId><Url>http://stackoverflow.com/questions/19740109</Url><Stack><Type>Unauthorized</Type><Message>Unauthorized (HTTP 401)</Message><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/shell.py</File><Line>737</Line><Method>main</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/shell.py</File><Line>673</Line><Method>main</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/v1_1/shell.py</File><Line>915</Line><Method>do_image_list</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/v1_1/images.py</File><Line>54</Line><Method>list</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/base.py</File><Line>61</Line><Method>_list</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/client.py</File><Line>229</Line><Method>get</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/novaclient/client.py</File><Line>226</Line><Method>_cs_request</Method></Frame></Stack></Post></Posts>