<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>463215</PostId><Url>http://stackoverflow.com/questions/463215</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 1146-1147: ordinal not in range(128)</Message><Frame><File>[...]\test.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>507123</PostId><Url>http://stackoverflow.com/questions/507123</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u0101'</Message><Frame><File>TestPrintEncoding.py</File><Line>22</Line><Method>[module]</Method></Frame><Frame><File>C:\Python30\lib\io.py</File><Line>1491</Line><Method>write</Method></Frame><Frame><File>C:\Python30\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>637396</PostId><Url>http://stackoverflow.com/questions/637396</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)</Message><Frame><File>parse.py</File><Line>79</Line><Method>module</Method></Frame><Frame><File>parse.py</File><Line>33</Line><Method>parseit</Method></Frame></Stack></Post><Post><PostId>787935</PostId><Url>http://stackoverflow.com/questions/787935</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\ufffd' in position 9: ordinal not in range(128)</Message><Frame><File>snip /account/paypal/views.py</File><Line>108</Line><Method>process_paypal_ipn</Method></Frame><Frame><File>snip /account/paypal/views.py</File><Line>41</Line><Method>send_response_to_paypal</Method></Frame><Frame><File>/usr/local/lib/python2.6/urllib.py</File><Line>1261</Line><Method>urlencode</Method></Frame></Stack></Post><Post><PostId>1058995</PostId><Url>http://stackoverflow.com/questions/1058995</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 2: ordinal not in range(128)</Message><Frame><File>hockey.py</File><Line>18</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>1077564</PostId><Url>http://stackoverflow.com/questions/1077564</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 73-75: ordinal not in range(128)</Message><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/webapp/__init__.py</File><Line>501</Line><Method>__call__</Method></Frame><Frame><File>/Users/johnb/Sites/hurl/hurl.py</File><Line>153</Line><Method>get</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/webapp/__init__.py</File><Line>371</Line><Method>redirect</Method></Frame></Stack></Post><Post><PostId>1569076</PostId><Url>http://stackoverflow.com/questions/1569076</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 46-48:</Message><Frame><File>test.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>c:\Python26\lib\site-packages\libxml2.py</File><Line>1237</Line><Method>parseDoc</Method></Frame></Stack></Post><Post><PostId>1652904</PostId><Url>http://stackoverflow.com/questions/1652904</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 1005: ordinal not in range(128)</Message><Frame><File>C:\Python26\Test2.py</File><Line>26</Line><Method>test_untitled</Method></Frame></Stack></Post><Post><PostId>1653569</PostId><Url>http://stackoverflow.com/questions/1653569</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 1005: ordinal not in range(128)</Message><Frame><File>C:\Python26\Test2.py</File><Line>26</Line><Method>test_untitled</Method></Frame></Stack></Post><Post><PostId>1787497</PostId><Url>http://stackoverflow.com/questions/1787497</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u5377' in position 3: character maps to</Message><Frame><File>C:\Documents and Settings\Michael Mao\Desktop\test.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\tools\Python31\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>1910427</PostId><Url>http://stackoverflow.com/questions/1910427</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 44-46: ordinal not in range(128)</Message><Frame><File>/usr/lib/python2.5/site- packages/Django-1.1.1-py2.5.egg/django/core/handlers/base.py</File><Line>92</Line><Method>get_response</Method></Frame><Frame><File>/usr/lib/python2.5/site-packages/Django-1.1.1-py2.5.egg/django/views/static.py</File><Line>51</Line><Method>serve</Method></Frame><Frame><File>/usr/lib/python2.5/posixpath.py</File><Line>195</Line><Method>isdir</Method></Frame></Stack></Post><Post><PostId>2018058</PostId><Url>http://stackoverflow.com/questions/2018058</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 81: ordinal not in range(128)</Message><Frame><File>Saving_fuction_added.py</File><Line>52</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>2025041</PostId><Url>http://stackoverflow.com/questions/2025041</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>D:\zjm_code\a.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>2224130</PostId><Url>http://stackoverflow.com/questions/2224130</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf1' in position 9: ordinal not in range(128)</Message><Frame><File>example.py</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>2265270</PostId><Url>http://stackoverflow.com/questions/2265270</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u092f' in position 0: ordinal not in range(128)</Message><Frame><File>transliterate_eh_nw.py</File><Line>43</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>2352234</PostId><Url>http://stackoverflow.com/questions/2352234</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\x80' in position 0: character maps to</Message><Frame><File>C:\test\char.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Python31\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>2389643</PostId><Url>http://stackoverflow.com/questions/2389643</Url><Stack><Type>UnicodeEncodeError</Type><Message>'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)</Message><Frame><File>test.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>2554545</PostId><Url>http://stackoverflow.com/questions/2554545</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf4' in position 35: ordinal not in range(128)</Message><Frame><File>my_file.py</File><Line>25</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>3077752</PostId><Url>http://stackoverflow.com/questions/3077752</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 37-40: character maps to</Message><Frame><File>test.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>PortablePython\App\lib\io.py</File><Line>1494</Line><Method>write</Method></Frame><Frame><File>PortablePython\App\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>3080373</PostId><Url>http://stackoverflow.com/questions/3080373</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)</Message><Frame><File>pyshell#23</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>3121186</PostId><Url>http://stackoverflow.com/questions/3121186</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb4' in position 19: ordinal not in range(128)</Message><Frame><File>playkud.py</File><Line>44</Line><Method>module</Method></Frame><Frame><File>playkud.py</File><Line>29</Line><Method>main</Method></Frame><Frame><File>/home/diegueus9/workspace/playku/src/client/playkud/crawler/crawler.py</File><Line>76</Line><Method>craw</Method></Frame><Frame><File>/home/diegueus9/workspace/playku/src/client/playkud/crawler/crawler.py</File><Line>58</Line><Method>index</Method></Frame><Frame><File>/home/diegueus9/workspace/playku/src/client/playkud/service.py</File><Line>32</Line><Method>add_song</Method></Frame><Frame><File>/home/diegueus9/workspace/playku/src/client/playkud/service.py</File><Line>14</Line><Method>make_request</Method></Frame><Frame><File>/usr/lib/python2.5/urllib.py</File><Line>1250</Line><Method>urlencode</Method></Frame></Stack></Post><Post><PostId>3151433</PostId><Url>http://stackoverflow.com/questions/3151433</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x92' in position 18: ordinal not in range(128)</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>513</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/autominer1/1.343038273644030157/siteinfo.py</File><Line>2160</Line><Method>post</Method></Frame></Stack></Post><Post><PostId>3479422</PostId><Url>http://stackoverflow.com/questions/3479422</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)</Message><Frame><File>./mr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/base.py</File><Line>195</Line><Method>run_from_argv</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/base.py</File><Line>222</Line><Method>execute</Method></Frame><Frame><File>/usr/local/cluster/dynamic/website/video/remmedia/management/commands/remmedia.py</File><Line>50</Line><Method>handle</Method></Frame><Frame><File>/usr/local/cluster/dynamic/website/video/remmedia/management/commands/remmedia.py</File><Line>117</Line><Method>FirstTimeLoad</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/manager.py</File><Line>123</Line><Method>get_or_create</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/query.py</File><Line>335</Line><Method>get_or_create</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/base.py</File><Line>410</Line><Method>save</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/base.py</File><Line>495</Line><Method>save_base</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/manager.py</File><Line>177</Line><Method>_insert</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/query.py</File><Line>1087</Line><Method>insert_query</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/sql/subqueries.py</File><Line>320</Line><Method>execute_sql</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/models/sql/query.py</File><Line>2369</Line><Method>execute_sql</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/db/backends/mysql/base.py</File><Line>84</Line><Method>execute</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/MySQLdb/cursors.py</File><Line>158</Line><Method>execute</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/MySQLdb/connections.py</File><Line>265</Line><Method>literal</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/MySQLdb/connections.py</File><Line>198</Line><Method>string_literal</Method></Frame></Stack></Post><Post><PostId>3480639</PostId><Url>http://stackoverflow.com/questions/3480639</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)</Message><Frame><File>./manage.py</File><Line>16</Line><Method>module</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/__init__.py</File><Line>362</Line><Method>execute_manager</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/__init__.py</File><Line>303</Line><Method>execute</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/base.py</File><Line>195</Line><Method>run_from_argv</Method></Frame><Frame><File>/usr/local/cluster/dynamic/virtualenv/lib/python2.5/site-packages/django/core/management/base.py</File><Line>222</Line><Method>execute</Method></Frame><Frame><File>/usr/local/cluster/dynamic/website/video/remmedia/management/commands/remmedia.py</File><Line>50</Line><Method>handle</Method></Frame><Frame><File>/usr/local/cluster/dynamic/website/video/remmedia/management/commands/remmedia.py</File><Line>115</Line><Method>FirstTimeLoad</Method></Frame><Frame><File>/usr/lib/python2.5/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>3480962</PostId><Url>http://stackoverflow.com/questions/3480962</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>3585717</PostId><Url>http://stackoverflow.com/questions/3585717</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#39</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>3667875</PostId><Url>http://stackoverflow.com/questions/3667875</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf5' in position 1: ordinal not in range(128)</Message><Frame><File>pyshell#79</File><Line>1</Line><Method>module</Method></Frame><Frame><File>pyshell#81</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>3667875</PostId><Url>http://stackoverflow.com/questions/3667875</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf5' in position 1: ordinal not in range(128)</Message><Frame><File>pyshell#79</File><Line>1</Line><Method>module</Method></Frame><Frame><File>pyshell#81</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>3810302</PostId><Url>http://stackoverflow.com/questions/3810302</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-50: ordinal not in range(128)</Message><Frame><File>/home/woodnt/python/10_day_forecast.py</File><Line>129</Line><Method>module</Method></Frame><Frame><File>/home/woodnt/python/lib/box.py</File><Line>24</Line><Method>line_lower</Method></Frame><Frame><File>/home/woodnt/python/10_day_forecast.py</File><Line>129</Line><Method>module</Method></Frame><Frame><File>/home/woodnt/python/lib/box.py</File><Line>24</Line><Method>line_lower</Method></Frame></Stack></Post><Post><PostId>3810302</PostId><Url>http://stackoverflow.com/questions/3810302</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-50: ordinal not in range(128)</Message><Frame><File>/home/woodnt/python/10_day_forecast.py</File><Line>129</Line><Method>module</Method></Frame><Frame><File>/home/woodnt/python/lib/box.py</File><Line>24</Line><Method>line_lower</Method></Frame><Frame><File>/home/woodnt/python/10_day_forecast.py</File><Line>129</Line><Method>module</Method></Frame><Frame><File>/home/woodnt/python/lib/box.py</File><Line>24</Line><Method>line_lower</Method></Frame></Stack></Post><Post><PostId>4233227</PostId><Url>http://stackoverflow.com/questions/4233227</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u2660' in position 0: character maps</Message><Frame><File>J:\test\symbol2.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>J:\Python26\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame><Frame><File>symbol2.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>d:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>4233227</PostId><Url>http://stackoverflow.com/questions/4233227</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u2660' in position 0: character maps</Message><Frame><File>J:\test\symbol2.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>J:\Python26\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame><Frame><File>symbol2.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>d:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>4551045</PostId><Url>http://stackoverflow.com/questions/4551045</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u9a6c' in position 14: character maps to</Message><Frame><File>C:\ex.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\ex.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>4551045</PostId><Url>http://stackoverflow.com/questions/4551045</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u9a6c' in position 14: character maps to</Message><Frame><File>C:\ex.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\ex.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>4601912</PostId><Url>http://stackoverflow.com/questions/4601912</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character '\u2019' in position 33777: ordinal not in range(128)</Message><Frame><File>/home/public/projects/proxy/script.cgi</File><Line>11</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python3.0/io.py</File><Line>1491</Line><Method>write</Method></Frame><Frame><File>/usr/local/lib/python3.0/encodings/ascii.py</File><Line>22</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>4718161</PostId><Url>http://stackoverflow.com/questions/4718161</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128)</Message><Frame><File>convert_folder_to_csv_PLAYER.py</File><Line>139</Line><Method>module</Method></Frame><Frame><File>convert_folder_to_csv_PLAYER.py</File><Line>121</Line><Method>xml2csv_PLAYER</Method></Frame></Stack></Post><Post><PostId>4799917</PostId><Url>http://stackoverflow.com/questions/4799917</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u20ac' in position 1945: ordinal not in range(128)</Message><Frame><File>scfbp.py</File><Line>203</Line><Method>myFunctionPage</Method></Frame></Stack></Post><Post><PostId>5141559</PostId><Url>http://stackoverflow.com/questions/5141559</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xef' in position 0: ordinal not in range(128)</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>517</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/parsepython/1.348669006354245654/mapreduce/base_handler.py</File><Line>59</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/parsepython/1.348669006354245654/mapreduce/handlers.py</File><Line>168</Line><Method>handle</Method></Frame><Frame><File>/base/data/home/apps/parsepython/1.348669006354245654/mapreduce/handlers.py</File><Line>233</Line><Method>process_entity</Method></Frame><Frame><File>/base/data/home/apps/parsepython/1.348669006354245654/parseXML.py</File><Line>71</Line><Method>process</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/xml/sax/expatreader.py</File><Line>107</Line><Method>parse</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/xml/sax/xmlreader.py</File><Line>123</Line><Method>parse</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/xml/sax/expatreader.py</File><Line>207</Line><Method>feed</Method></Frame><Frame><File>/base/data/home/apps/parsepython/1.348669006354245654/parseXML.py</File><Line>136</Line><Method>characters</Method></Frame></Stack></Post><Post><PostId>5245904</PostId><Url>http://stackoverflow.com/questions/5245904</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa9' in position 10: ordi</Message><Frame><File>input</File><Line>1</Line><Method>module</Method></Frame><Frame><File>input</File><Line>3</Line><Method>__repr__</Method></Frame></Stack></Post><Post><PostId>5340003</PostId><Url>http://stackoverflow.com/questions/5340003</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 21-26: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.6/dist-packages/twisted/python/reflect.py</File><Line>546</Line><Method>_safeFormat</Method></Frame></Stack></Post><Post><PostId>5341012</PostId><Url>http://stackoverflow.com/questions/5341012</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)</Message><Frame><File>/usr/lib/python2.6/dist-packages/twisted/python/reflect.py</File><Line>560</Line><Method>safe_str</Method></Frame></Stack></Post><Post><PostId>5541040</PostId><Url>http://stackoverflow.com/questions/5541040</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 313: ordinal not in range(128)</Message><Frame><File>/base/data/home/apps/myapp/1.349473606437967000/myfile.py</File><Line>137</Line><Method>get</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file.py</File><Line>364</Line><Method>write</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file.py</File><Line>472</Line><Method>_make_rpc_call_with_retry</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file.py</File><Line>226</Line><Method>_make_call</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>509</Line><Method>make_call</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>115</Line><Method>MakeCall</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/runtime/apiproxy.py</File><Line>161</Line><Method>_MakeCallImpl</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/net/proto/ProtocolBuffer.py</File><Line>204</Line><Method>Output</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file_service_pb.py</File><Line>2390</Line><Method>OutputUnchecked</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/net/proto/ProtocolBuffer.py</File><Line>432</Line><Method>putPrefixedString</Method></Frame></Stack></Post><Post><PostId>5547066</PostId><Url>http://stackoverflow.com/questions/5547066</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u0171' in position 0: character maps to</Message><Frame><File>C:\ex.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>5664414</PostId><Url>http://stackoverflow.com/questions/5664414</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2019' in position 1075: ordinal not in range(128)</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>634</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/my-app-ip/django2.349712625627523096/main.py</File><Line>2246</Line><Method>get</Method></Frame><Frame><File>/base/data/home/apps/my-app-ip/django2.349712625627523096/main.py</File><Line>1618</Line><Method>compressBuf</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/gzip.py</File><Line>204</Line><Method>write</Method></Frame></Stack></Post><Post><PostId>5695421</PostId><Url>http://stackoverflow.com/questions/5695421</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u03a9' in position 6: character maps to</Message><Frame><File>Unicodetest.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\encodings\cp1252.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>5746888</PostId><Url>http://stackoverflow.com/questions/5746888</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe2' in position 131: ordinal not in range(128)</Message><Frame><File>terminalHN.py</File><Line>19</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>6098482</PostId><Url>http://stackoverflow.com/questions/6098482</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)</Message><Frame><File>db_import.py</File><Line>222</Line><Method>module</Method></Frame><Frame><File>db_import.py</File><Line>219</Line><Method>main</Method></Frame><Frame><File>db_import.py</File><Line>145</Line><Method>importieren</Method></Frame></Stack></Post><Post><PostId>6742053</PostId><Url>http://stackoverflow.com/questions/6742053</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character</Message><Frame><File>./test.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>6788158</PostId><Url>http://stackoverflow.com/questions/6788158</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u20ac' in position</Message><Frame><File>uniCode.py</File><Line>18</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>6981594</PostId><Url>http://stackoverflow.com/questions/6981594</Url><Stack><Type>UnicodeEncodeError</Type><Message>'utf-8' codec can't encode character '\udce7' in position 4: surrogates not allowed</Message><Frame><File>argv.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>7028996</PostId><Url>http://stackoverflow.com/questions/7028996</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u2019' in position 9: character maps to</Message><Frame><File>C:\Documents and Settings\metolone\Desktop\x.py</File><Line>10</Line><Method>module</Method></Frame><Frame><File>C:\dev\python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>7039975</PostId><Url>http://stackoverflow.com/questions/7039975</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 173: ordinal not in range(128)</Message><Frame><File>sendmail.py</File><Line>33</Line><Method>bulksend</Method></Frame><Frame><File>/usr/lib/python2.4/email/Message.py</File><Line>129</Line><Method>as_string</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>82</Line><Method>flatten</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>113</Line><Method>_write</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>139</Line><Method>_dispatch</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>205</Line><Method>_handle_multipart</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>82</Line><Method>flatten</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>113</Line><Method>_write</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>139</Line><Method>_dispatch</Method></Frame><Frame><File>/usr/lib/python2.4/email/Generator.py</File><Line>182</Line><Method>_handle_text</Method></Frame></Stack></Post><Post><PostId>7050044</PostId><Url>http://stackoverflow.com/questions/7050044</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 19:         ordinal not in range(128)</Message><Frame><File>test01.py</File><Line>40</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>7133572</PostId><Url>http://stackoverflow.com/questions/7133572</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u306e'</Message><Frame><File>MyScript.py</File><Line>20</Line><Method>module</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>7242275</PostId><Url>http://stackoverflow.com/questions/7242275</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\ue403' in position 77: character maps to</Message><Frame><File>C:\Programming\workspace\pim2smsbr\src\pim2smsbr.py</File><Line>207</Line><Method>module</Method></Frame><Frame><File>C:\Programming\workspace\pim2smsbr\src\pim2smsbr.py</File><Line>98</Line><Method>convert</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1252.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>7315629</PostId><Url>http://stackoverflow.com/questions/7315629</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe5' in position 5: ordinal not in range(128)</Message><Frame><File>l÷p.py</File><Line>92</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>7588575</PostId><Url>http://stackoverflow.com/questions/7588575</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)</Message><Frame><File>file_location</File><Line>38</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8108277</PostId><Url>http://stackoverflow.com/questions/8108277</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u04b7' in position 7: ordinal not in range(128)</Message><Frame><File>C:\Program Files\Google\google_appengine\google\appengine\ext\webapp\_webapp25.py</File><Line>701</Line><Method>__call__</Method></Frame><Frame><File>C:\Program Files\Google\google_appengine\demos\guestbook\guestbook.py</File><Line>47</Line><Method>get</Method></Frame></Stack></Post><Post><PostId>8129911</PostId><Url>http://stackoverflow.com/questions/8129911</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\x92' in position</Message><Frame><File>TATest.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>d:\python32\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>8222270</PostId><Url>http://stackoverflow.com/questions/8222270</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)</Message><Frame><File>./uc.py</File><Line>43</Line><Method>?</Method></Frame><Frame><File>./uc.py</File><Line>41</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8222270</PostId><Url>http://stackoverflow.com/questions/8222270</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)</Message><Frame><File>./uc.py</File><Line>43</Line><Method>?</Method></Frame><Frame><File>./uc.py</File><Line>41</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8290206</PostId><Url>http://stackoverflow.com/questions/8290206</Url><Stack><Type>UnicodeEncodeError</Type><Message>'latin-1' codec can't encode character u'\u2013' in position 3: ordinal not in range(256)</Message><Frame><File>TopLevelCategories.py</File><Line>267</Line><Method>module</Method></Frame><Frame><File>/opt/ts/python/2.7/lib/python2.7/site-packages/MySQLdb/cursors.py</File><Line>158</Line><Method>execute</Method></Frame><Frame><File>/opt/ts/python/2.7/lib/python2.7/site-packages/MySQLdb/connections.py</File><Line>265</Line><Method>literal</Method></Frame><Frame><File>/opt/ts/python/2.7/lib/python2.7/site-packages/MySQLdb/connections.py</File><Line>203</Line><Method>unicode_literal</Method></Frame></Stack></Post><Post><PostId>8365660</PostId><Url>http://stackoverflow.com/questions/8365660</Url><Stack><Type>UnicodeEncodeError</Type><Message>'latin-1' codec can't encode characters in position 204-230: ordinal not in range(256)</Message><Frame><File>YahooQueryData.py</File><Line>78</Line><Method>module</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/MySQLdb/cursors.py</File><Line>159</Line><Method>execute</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/MySQLdb/connections.py</File><Line>264</Line><Method>literal</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/MySQLdb/connections.py</File><Line>202</Line><Method>unicode_literal</Method></Frame></Stack></Post><Post><PostId>8481006</PostId><Url>http://stackoverflow.com/questions/8481006</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf6' in position 10: ordinal not in range(128)</Message><Frame><File>./CyberJukebox.py</File><Line>489</Line><Method>on_stats_to_clipboard</Method></Frame><Frame><File>/home/nine/dev/python/CyberJukebox/jukebox.py</File><Line>235</Line><Method>get_stats</Method></Frame><Frame><File>/home/nine/dev/python/CyberJukebox/jukebox.py</File><Line>59</Line><Method>get_string</Method></Frame><Frame><File>/home/nine/dev/python/CyberJukebox/jukebox.py</File><Line>59</Line><Method>genexpr</Method></Frame><Frame><File>/usr/lib/python2.7/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>8629792</PostId><Url>http://stackoverflow.com/questions/8629792</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)</Message><Frame><File>./grablinks</File><Line>101</Line><Method>module</Method></Frame><Frame><File>./grablinks</File><Line>88</Line><Method>main</Method></Frame><Frame><File>./grablinks</File><Line>36</Line><Method>grab_links</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/BeautifulSoup.py</File><Line>1519</Line><Method>__init__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/BeautifulSoup.py</File><Line>1144</Line><Method>__init__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/BeautifulSoup.py</File><Line>1186</Line><Method>_feed</Method></Frame><Frame><File>/usr/lib/python2.7/sgmllib.py</File><Line>104</Line><Method>feed</Method></Frame><Frame><File>/usr/lib/python2.7/sgmllib.py</File><Line>143</Line><Method>goahead</Method></Frame><Frame><File>/usr/lib/python2.7/sgmllib.py</File><Line>320</Line><Method>parse_endtag</Method></Frame><Frame><File>/usr/lib/python2.7/sgmllib.py</File><Line>358</Line><Method>finish_endtag</Method></Frame></Stack></Post><Post><PostId>8636795</PostId><Url>http://stackoverflow.com/questions/8636795</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>/Users/.../main.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8688274</PostId><Url>http://stackoverflow.com/questions/8688274</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xed' in position 112: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>7</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8727490</PostId><Url>http://stackoverflow.com/questions/8727490</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2026' in position 29: character maps to</Message><Frame><File>Mailgen.py</File><Line>378</Line><Method>module</Method></Frame><Frame><File>Mailgen.py</File><Line>210</Line><Method>mark_markup</Method></Frame><Frame><File>c:\python32\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>8798591</PostId><Url>http://stackoverflow.com/questions/8798591</Url><Stack><Type>UnicodeEncodeError</Type><Message>'mbcs' codec can't encode characters in position 0--1: inval</Message><Frame><File>module8.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8963737</PostId><Url>http://stackoverflow.com/questions/8963737</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>ex.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>8996911</PostId><Url>http://stackoverflow.com/questions/8996911</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 16-21: character maps to</Message><Frame><File>TestSparql.py</File><Line>172</Line><Method>module</Method></Frame><Frame><File>C:\Python27\Lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>9208802</PostId><Url>http://stackoverflow.com/questions/9208802</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 52-54: ordinal not in range(128)</Message><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/core/handlers/base.py</File><Line>111</Line><Method>get_response</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/contrib/admin/options.py</File><Line>307</Line><Method>wrapper</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/utils/decorators.py</File><Line>93</Line><Method>_wrapped_view</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/views/decorators/cache.py</File><Line>79</Line><Method>_wrapped_view_func</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/contrib/admin/sites.py</File><Line>197</Line><Method>inner</Method></Frame><Frame><File>/srv/django/letebo/app/cms/admin.py</File><Line>81</Line><Method>change_view</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/utils/decorators.py</File><Line>28</Line><Method>_wrapper</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/utils/decorators.py</File><Line>93</Line><Method>_wrapped_view</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/utils/decorators.py</File><Line>24</Line><Method>bound_func</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/transaction.py</File><Line>217</Line><Method>inner</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/contrib/admin/options.py</File><Line>985</Line><Method>change_view</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/contrib/admin/options.py</File><Line>677</Line><Method>save_formset</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/forms/models.py</File><Line>482</Line><Method>save</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/forms/models.py</File><Line>613</Line><Method>save_new_objects</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/forms/models.py</File><Line>717</Line><Method>save_new</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/models/base.py</File><Line>460</Line><Method>save</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/models/base.py</File><Line>504</Line><Method>save_base</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/models/base.py</File><Line>543</Line><Method>save_base</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/models/fields/files.py</File><Line>255</Line><Method>pre_save</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/db/models/fields/files.py</File><Line>92</Line><Method>save</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/core/files/storage.py</File><Line>48</Line><Method>save</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/core/files/storage.py</File><Line>74</Line><Method>get_available_name</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/site-packages/django/core/files/storage.py</File><Line>218</Line><Method>exists</Method></Frame><Frame><File>/srv/.virtualenvs/letebo/lib/python2.6/genericpath.py</File><Line>18</Line><Method>exists</Method></Frame></Stack></Post><Post><PostId>9235376</PostId><Url>http://stackoverflow.com/questions/9235376</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 28: ordinal not in range(128)</Message><Frame><File>run_anatomy_client.py</File><Line>19</Line><Method>module</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/application/myapp/client.py</File><Line>282</Line><Method>main</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/application/myapp/client.py</File><Line>76</Line><Method>sync_customer</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/query.py</File><Line>113</Line><Method>__nonzero__</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/query.py</File><Line>107</Line><Method>_result_iter</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/query.py</File><Line>772</Line><Method>_fill_cache</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/query.py</File><Line>273</Line><Method>iterator</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py</File><Line>680</Line><Method>results_iter</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py</File><Line>735</Line><Method>execute_sql</Method></Frame><Frame><File>/Users/user/Documents/workspace/Wawi/pyenv/lib/python2.7/site-packages/django/db/backends/util.py</File><Line>43</Line><Method>execute</Method></Frame></Stack></Post><Post><PostId>9321811</PostId><Url>http://stackoverflow.com/questions/9321811</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 19-25: character     maps to</Message><Frame><File>C:\---\---\---\---.py</File><Line>4</Line><Method>module</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>9368495</PostId><Url>http://stackoverflow.com/questions/9368495</Url><Stack><Type>UnicodeEncodeError</Type><Message>'latin-1' codec can't encode character u'\u201c' in position 1638: ordinal not in range(256)</Message><Frame><File>C:\Python26\Lib\site-packages\pythonwin\pywin\framework\editor\document.py</File><Line>77</Line><Method>OnSaveDocument</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\pythonwin\pywin\scintilla\document.py</File><Line>54</Line><Method>SaveFile</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\pythonwin\pywin\scintilla\view.py</File><Line>394</Line><Method>SaveTextFile</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\pythonwin\pywin\scintilla\document.py</File><Line>155</Line><Method>_SaveTextToFile</Method></Frame></Stack></Post><Post><PostId>9620085</PostId><Url>http://stackoverflow.com/questions/9620085</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 20-21: character maps to</Message><Frame><File>pyshell#19</File><Line>1</Line><Method>-toplevel-</Method></Frame><Frame><File>C:\Python24\lib\encodings\cp1252.py</File><Line>18</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>9628793</PostId><Url>http://stackoverflow.com/questions/9628793</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\xd7' in position 3</Message><Frame><File>c:\Python27\lib\threading.py</File><Line>530</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>c:\Python27\lib\site-packages\Skype4Py\utils.py</File><Line>225</Line><Method>run</Method></Frame><Frame><File>s.py</File><Line>38</Line><Method>OnMessageStatus</Method></Frame><Frame><File>s.py</File><Line>18</Line><Method>wolfram</Method></Frame><Frame><File>c:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>9674910</PostId><Url>http://stackoverflow.com/questions/9674910</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u201c' in position 0: ordinal not in range(128)</Message><Frame><File>C:\Documents and Settings\mine\Desktop\test_lxml.py</File><Line>77</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>9747090</PostId><Url>http://stackoverflow.com/questions/9747090</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)</Message><Frame><File>C:\dev\python\query-1.py</File><Line>24</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\adodbapi\adodbapi.py</File><Line>651</Line><Method>__str__</Method></Frame></Stack></Post><Post><PostId>9752521</PostId><Url>http://stackoverflow.com/questions/9752521</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf6' in position 26:</Message><Frame><File>./client.py</File><Line>180</Line><Method>sendMess</Method></Frame></Stack></Post><Post><PostId>9822655</PostId><Url>http://stackoverflow.com/questions/9822655</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)</Message><Frame><File>writer.py</File><Line>46</Line><Method>module</Method></Frame><Frame><File>writer.py</File><Line>33</Line><Method>write_listings</Method></Frame><Frame><File>c:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame><Frame><File>test.py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>9822655</PostId><Url>http://stackoverflow.com/questions/9822655</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)</Message><Frame><File>writer.py</File><Line>46</Line><Method>module</Method></Frame><Frame><File>writer.py</File><Line>33</Line><Method>write_listings</Method></Frame><Frame><File>c:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame><Frame><File>test.py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>9871346</PostId><Url>http://stackoverflow.com/questions/9871346</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\ufeff' in position 0: character maps to</Message><Frame><File>C:\Users\Rendszergazda\workspace\achievements\hiba.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1250.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>9880173</PostId><Url>http://stackoverflow.com/questions/9880173</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 3-5: ordinal not in range(128)</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py</File><Line>703</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~kaon-log/2.357769827131038147/main.py</File><Line>143</Line><Method>post</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>9942594</PostId><Url>http://stackoverflow.com/questions/9942594</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 20: ordinal not in range(128)</Message><Frame><File>foobar.py</File><Line>792</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>9954948</PostId><Url>http://stackoverflow.com/questions/9954948</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 2-4: character maps to</Message><Frame><File>E:\...\FirstModule.py</File><Line>31</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1252.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>10018271</PostId><Url>http://stackoverflow.com/questions/10018271</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf8' in position 264</Message><Frame><File>script.py</File><Line>70</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10091737</PostId><Url>http://stackoverflow.com/questions/10091737</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf1' in position 10: ordinal not in range(128)</Message><Frame><File>procesar.py</File><Line>8</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10105796</PostId><Url>http://stackoverflow.com/questions/10105796</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u03b9' in position 10:      character maps to</Message><Frame><File>C:\Users\chatterjees\workspace\de.vogella.python.first\src\top_100_thread.py</File><Line>21</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1252.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>10143139</PostId><Url>http://stackoverflow.com/questions/10143139</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 0-1: character maps to</Message><Frame><File>qtest1.py</File><Line>15</Line><Method>print(by.decode('big5'))</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>10149961</PostId><Url>http://stackoverflow.com/questions/10149961</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 97-102: or</Message><Frame><File>C:\Scripts\iQuality\test.py</File><Line>47</Line><Method>module</Method></Frame><Frame><File>C:\Scripts\iQuality\test.py</File><Line>26</Line><Method>spellFix</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>955</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>989</Line><Method>_send_request</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>951</Line><Method>endheaders</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>815</Line><Method>_send_output</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>787</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>220</Line><Method>sendall</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>189</Line><Method>send</Method></Frame></Stack></Post><Post><PostId>10217871</PostId><Url>http://stackoverflow.com/questions/10217871</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 1-2: cha</Message><Frame><File>echofile.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>10358039</PostId><Url>http://stackoverflow.com/questions/10358039</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\xf8' in position 6</Message><Frame><File>BFICrawl.py</File><Line>20</Line><Method>module</Method></Frame><Frame><File>C:\Python27\LIB\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>10396141</PostId><Url>http://stackoverflow.com/questions/10396141</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb4' in position 52: ordinal not in range(128)</Message><Frame><File>/var/www/beta/env/lib/python2.7/site-packages/dblib-1.0dev3-py2.7.egg/dblib/orm/file.py</File><Line>169</Line><Method>get_thumbnail</Method></Frame><Frame><File>/usr/lib/python2.7/genericpath.py</File><Line>18</Line><Method>exists</Method></Frame></Stack></Post><Post><PostId>10470000</PostId><Url>http://stackoverflow.com/questions/10470000</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u0130' in position 17: ordinal not in range(128)</Message><Frame><File>/Library/Python/2.6/site-packages/django/core/servers/basehttp.py</File><Line>283</Line><Method>run</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/contrib/staticfiles/handlers.py</File><Line>68</Line><Method>__call__</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/core/handlers/wsgi.py</File><Line>272</Line><Method>__call__</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/core/handlers/base.py</File><Line>146</Line><Method>get_response</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/views/debug.py</File><Line>294</Line><Method>technical_404_response</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/utils/encoding.py</File><Line>123</Line><Method>smart_str</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/utils/encoding.py</File><Line>124</Line><Method>smart_str</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/core/urlresolvers.py</File><Line>191</Line><Method>__repr__</Method></Frame><Frame><File>/Library/Python/2.6/site-packages/django/core/urlresolvers.py</File><Line>191</Line><Method>__repr__</Method></Frame></Stack></Post><Post><PostId>10490816</PostId><Url>http://stackoverflow.com/questions/10490816</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 13: ordinal not in range(128)</Message><Frame><File>tmp_file.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10761851</PostId><Url>http://stackoverflow.com/questions/10761851</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)</Message><Frame><File>report.py</File><Line>104</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>30</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>129</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10761851</PostId><Url>http://stackoverflow.com/questions/10761851</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)</Message><Frame><File>report.py</File><Line>104</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>30</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>129</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10761851</PostId><Url>http://stackoverflow.com/questions/10761851</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)</Message><Frame><File>report.py</File><Line>104</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>30</Line><Method>module</Method></Frame><Frame><File>report.py</File><Line>129</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10872208</PostId><Url>http://stackoverflow.com/questions/10872208</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)</Message><Frame><File>snippetRetriver.py</File><Line>402</Line><Method>module</Method></Frame><Frame><File>snippetRetriver.py</File><Line>201</Line><Method>getSentenceList</Method></Frame><Frame><File>/usr/lib/python2.7/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>11050292</PostId><Url>http://stackoverflow.com/questions/11050292</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2019' in position 4537:character maps to</Message><Frame><File>C:\Python32\lib\logging\__init__.py</File><Line>939</Line><Method>emit</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>11061605</PostId><Url>http://stackoverflow.com/questions/11061605</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xd8' in position 11: ordinal not in range(128)</Message><Frame><File>./test.py</File><Line>12</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11353449</PostId><Url>http://stackoverflow.com/questions/11353449</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa1' in position 13: ordinal not in range(128)</Message><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py</File><Line>570</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~tester-sandbox/1.360113171877023968/website/sms.py</File><Line>22</Line><Method>post</Method></Frame></Stack></Post><Post><PostId>11471398</PostId><Url>http://stackoverflow.com/questions/11471398</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xc1' in position 5: ordinal not in range(128)</Message><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/webapp/_webapp25.py</File><Line>701</Line><Method>__call__</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/admin/__init__.py</File><Line>1704</Line><Method>get</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/admin/__init__.py</File><Line>1664</Line><Method>_ProcessSearchResponse</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/admin/__init__.py</File><Line>158</Line><Method>TruncateValue</Method></Frame></Stack></Post><Post><PostId>11592476</PostId><Url>http://stackoverflow.com/questions/11592476</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)</Message><Frame><File>ipython-input-36-85c1b388bd1b</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11735363</PostId><Url>http://stackoverflow.com/questions/11735363</Url><Stack><Type>UnicodeEncodeError</Type><Message>'utf-8' codec can't encode character '\udcc3' in position 56: surrogates not allowed</Message><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>365</Line><Method>_encodeFilenameFlags</Method></Frame><Frame><File>XBE.py</File><Line>45</Line><Method>main</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>62</Line><Method>executeList</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>71</Line><Method>executeActivity</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>112</Line><Method>exAct_FileBackup</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptFileManager.py</File><Line>143</Line><Method>zipFileList</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>1115</Line><Method>write</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>355</Line><Method>FileHeader</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>367</Line><Method>_encodeFilenameFlags</Method></Frame></Stack></Post><Post><PostId>11735363</PostId><Url>http://stackoverflow.com/questions/11735363</Url><Stack><Type>UnicodeEncodeError</Type><Message>'utf-8' codec can't encode character '\udcc3' in position 56: surrogates not allowed</Message><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>365</Line><Method>_encodeFilenameFlags</Method></Frame><Frame><File>XBE.py</File><Line>45</Line><Method>main</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>62</Line><Method>executeList</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>71</Line><Method>executeActivity</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptActivityManager.py</File><Line>112</Line><Method>exAct_FileBackup</Method></Frame><Frame><File>/home/vte/vtebackup/vte41/scripts/ptFileManager.py</File><Line>143</Line><Method>zipFileList</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>1115</Line><Method>write</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>355</Line><Method>FileHeader</Method></Frame><Frame><File>/usr/local/lib/python3.2/zipfile.py</File><Line>367</Line><Method>_encodeFilenameFlags</Method></Frame></Stack></Post><Post><PostId>11800499</PostId><Url>http://stackoverflow.com/questions/11800499</Url><Stack><Type>UnicodeEncodeError</Type><Message>'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)</Message><Frame><File>../pycli/samples/x.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11845065</PostId><Url>http://stackoverflow.com/questions/11845065</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe8' in position 3: ordinal not in range(128)</Message><Frame><File>x.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11884190</PostId><Url>http://stackoverflow.com/questions/11884190</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)</Message><Frame><File>makeCSV.py</File><Line>87</Line><Method>module</Method></Frame><Frame><File>makeCSV.py</File><Line>54</Line><Method>writerow</Method></Frame><Frame><File>makeCSV.py</File><Line>87</Line><Method>module</Method></Frame><Frame><File>makeCSV.py</File><Line>54</Line><Method>writerow</Method></Frame></Stack></Post><Post><PostId>11884190</PostId><Url>http://stackoverflow.com/questions/11884190</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)</Message><Frame><File>makeCSV.py</File><Line>87</Line><Method>module</Method></Frame><Frame><File>makeCSV.py</File><Line>54</Line><Method>writerow</Method></Frame><Frame><File>makeCSV.py</File><Line>87</Line><Method>module</Method></Frame><Frame><File>makeCSV.py</File><Line>54</Line><Method>writerow</Method></Frame></Stack></Post><Post><PostId>12053849</PostId><Url>http://stackoverflow.com/questions/12053849</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\xf6' in position 23: character maps to</Message><Frame><File>C:\Users\pem\workspace\a\src\a.py</File><Line>17</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1251.py</File><Line>15</Line><Method>decode</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1251.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>12086953</PostId><Url>http://stackoverflow.com/questions/12086953</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)</Message><Frame><File>unicodeerr1.py</File><Line>11</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>12188848</PostId><Url>http://stackoverflow.com/questions/12188848</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 8-10: ordinal not in range(128)</Message><Frame><File>process.py</File><Line>48</Line><Method>module</Method></Frame><Frame><File>process.py</File><Line>45</Line><Method>cyrillic</Method></Frame><Frame><File>C:\Python\27\Lib\subprocess.py</File><Line>679</Line><Method>__init__</Method></Frame><Frame><File>C:\Python\27\Lib\subprocess.py</File><Line>870</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>12496985</PostId><Url>http://stackoverflow.com/questions/12496985</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 24835-24836: character maps</Message><Frame><File>C:\WoMMaxX\lt_automation\Tools\LogParser.py</File><Line>375</Line><Method>module</Method></Frame><Frame><File>C:\WoMMaxX\lt_automation\Tools\LogParser.py</File><Line>196</Line><Method>analyze_longtails</Method></Frame><Frame><File>C:\Python\3.2\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>12545843</PostId><Url>http://stackoverflow.com/questions/12545843</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u201d' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#154</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\utf_32.py</File><Line>11</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>12546705</PostId><Url>http://stackoverflow.com/questions/12546705</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u201d' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#154</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\utf_32.py</File><Line>11</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>12825390</PostId><Url>http://stackoverflow.com/questions/12825390</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>test_mod.py</File><Line>14</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>12827256</PostId><Url>http://stackoverflow.com/questions/12827256</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 4: ordinal not in range(128)</Message><Frame><File>./export_debug.py</File><Line>18</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>12984110</PostId><Url>http://stackoverflow.com/questions/12984110</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe0' in position 14: ordinal not in range(128)</Message><Frame><File>TestingCodecs.py</File><Line>7</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13473861</PostId><Url>http://stackoverflow.com/questions/13473861</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 29-32: character maps to</Message><Frame><File>LanguageTesting.py</File><Line>71</Line><Method>module</Method></Frame><Frame><File>LanguageTesting.py</File><Line>43</Line><Method>parse_tweet</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>13510172</PostId><Url>http://stackoverflow.com/questions/13510172</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\x96' in position 10: character maps to</Message><Frame><File>bottle.py</File><Line>763</Line><Method>_handle</Method></Frame><Frame><File>bottle.py</File><Line>1572</Line><Method>wrapper</Method></Frame><Frame><File>dictionary.py</File><Line>63</Line><Method>request</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>13537308</PostId><Url>http://stackoverflow.com/questions/13537308</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xba' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#30</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13539141</PostId><Url>http://stackoverflow.com/questions/13539141</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb4' in position 0: ordinal not in range(128)</Message><Frame><File>/home/DISCO/data/comp1/46/Job@549:b4c76:9cbb1/usr/local/lib/python2.7/site-packages/disco/worker/__init__.py</File><Line>329</Line><Method>main</Method></Frame><Frame><File>/home/DISCO/data/comp1/46/Job@549:b4c76:9cbb1/usr/local/lib/python2.7/site-packages/disco/worker/__init__.py</File><Line>290</Line><Method>start</Method></Frame><Frame><File>/home/DISCO/data/comp1/46/Job@549:b4c76:9cbb1/usr/local/lib/python2.7/site-packages/disco/worker/classic/worker.py</File><Line>286</Line><Method>run</Method></Frame><Frame><File>/home/DISCO/data/comp1/46/Job@549:b4c76:9cbb1/usr/local/lib/python2.7/site-packages/disco/worker/classic/worker.py</File><Line>302</Line><Method>map</Method></Frame><Frame><File>/home/DISCO/data/comp1/46/Job@549:b4c76:9cbb1/usr/local/lib/python2.7/site-packages/disco/worker/classic/func.py</File><Line>341</Line><Method>default_partition</Method></Frame></Stack></Post><Post><PostId>13665819</PostId><Url>http://stackoverflow.com/questions/13665819</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character 'u\u2665' in position 0: character maps to</Message><Frame><File>C:python33\meh.py</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>13674663</PostId><Url>http://stackoverflow.com/questions/13674663</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf4' in position 0: ordinal not in range(128)</Message><Frame><File>./unicodetest.py</File><Line>10</Line><Method>module</Method></Frame><Frame><File>./unicodetest.py</File><Line>6</Line><Method>unicode_test</Method></Frame></Stack></Post><Post><PostId>13738722</PostId><Url>http://stackoverflow.com/questions/13738722</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb0' in position 2: ordinal not in range(128)</Message><Frame><File>/home/naftuli/Documents/i7zdaemon/get-i7z-value</File><Line>85</Line><Method>module</Method></Frame><Frame><File>/home/naftuli/Documents/i7zdaemon/get-i7z-value</File><Line>28</Line><Method>main</Method></Frame><Frame><File>/home/naftuli/Documents/i7zdaemon/get-i7z-value</File><Line>63</Line><Method>get_temp_value</Method></Frame></Stack></Post><Post><PostId>13828688</PostId><Url>http://stackoverflow.com/questions/13828688</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>/home/mdenson/projects/test.py</File><Line>20</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13838508</PostId><Url>http://stackoverflow.com/questions/13838508</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x80' in position 0: ordinal not in range(128)</Message><Frame><File>./asd.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13875566</PostId><Url>http://stackoverflow.com/questions/13875566</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u5a07' in position 10:    ordinal    not in range(128)</Message><Frame><File>keywords.py</File><Line>31</Line><Method>module</Method></Frame><Frame><File>keywords.py</File><Line>28</Line><Method>main</Method></Frame><Frame><File>keywords.py</File><Line>19</Line><Method>get_csv</Method></Frame></Stack></Post><Post><PostId>13923355</PostId><Url>http://stackoverflow.com/questions/13923355</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14067575</PostId><Url>http://stackoverflow.com/questions/14067575</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 29: ordinal not in range(128)</Message><Frame><File>pyshell#86</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\vobject-0.8.1c-py2.7.egg\vobject\base.py</File><Line>1078</Line><Method>readOne</Method></Frame><Frame><File>C:\Python27\lib\site-packages\vobject-0.8.1c-py2.7.egg\vobject\base.py</File><Line>1031</Line><Method>readComponents</Method></Frame><Frame><File>C:\Python27\lib\site-packages\vobject-0.8.1c-py2.7.egg\vobject\base.py</File><Line>888</Line><Method>textLineToContentLine</Method></Frame><Frame><File>C:\Python27\lib\site-packages\vobject-0.8.1c-py2.7.egg\vobject\base.py</File><Line>262</Line><Method>__init__</Method></Frame></Stack></Post><Post><PostId>14149460</PostId><Url>http://stackoverflow.com/questions/14149460</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u201c' in position 0: character maps to</Message><Frame><File>C:\Python27\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>14163801</PostId><Url>http://stackoverflow.com/questions/14163801</Url><Stack><Type>UnicodeEncodeError</Type><Message>'utf-8' codec can't encode character '\ud800' in position 16383: surrogates not allowed</Message><Frame><File>path to above file</File><Line>26</Line><Method>foo</Method></Frame><Frame><File>C:\Python32\lib\xml\etree\ElementTree.py</File><Line>1314</Line><Method>__next__</Method></Frame><Frame><File>C:\Python32\lib\xml\etree\ElementTree.py</File><Line>1668</Line><Method>feed</Method></Frame></Stack></Post><Post><PostId>14173421</PostId><Url>http://stackoverflow.com/questions/14173421</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-51: ordinal not in range(128)</Message><Frame><File>translit_error.py</File><Line>124</Line><Method>module</Method></Frame><Frame><File>translit_error.py</File><Line>103</Line><Method>translit2</Method></Frame></Stack></Post><Post><PostId>14177118</PostId><Url>http://stackoverflow.com/questions/14177118</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xdf' in position 3:ordinal not in range(128)</Message><Frame><File>C:\Users\cristina\Documents\horia\Linguistics3\px t3.py</File><Line>68</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14238824</PostId><Url>http://stackoverflow.com/questions/14238824</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 170: ordinal not in range(128)</Message><Frame><File>unicode-test.py</File><Line>19</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14284269</PostId><Url>http://stackoverflow.com/questions/14284269</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\xdf' in position 0: character maps to</Message><Frame><File>.\tmp.py</File><Line>3</Line><Method>module</Method></Frame><Frame><File>C:\Python32\lib\encodings\cp866.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>14412907</PostId><Url>http://stackoverflow.com/questions/14412907</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)</Message><Frame><File>./ScrapeTemplate.py</File><Line>30</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14441266</PostId><Url>http://stackoverflow.com/questions/14441266</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/application.py</File><Line>239</Line><Method>process</Method></Frame><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/application.py</File><Line>230</Line><Method>handle</Method></Frame><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/application.py</File><Line>420</Line><Method>_delegate</Method></Frame><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/application.py</File><Line>396</Line><Method>handle_class</Method></Frame><Frame><File>/home/mkbnetadm/netadmin/na.py</File><Line>36</Line><Method>POST</Method></Frame><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/form.py</File><Line>76</Line><Method>validates</Method></Frame><Frame><File>/usr/local/lib/python2.6/dist-packages/web.py-0.37-py2.6.egg/web/form.py</File><Line>18</Line><Method>attrget</Method></Frame></Stack></Post><Post><PostId>14465492</PostId><Url>http://stackoverflow.com/questions/14465492</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 62-63:     character maps to</Message><Frame><File>C:\work\test.py</File><Line>69</Line><Method>module</Method></Frame><Frame><File>C:\work\test.py</File><Line>65</Line><Method>main</Method></Frame><Frame><File>C:\work\test.py</File><Line>48</Line><Method>displayFileOld</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>14542073</PostId><Url>http://stackoverflow.com/questions/14542073</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 750: ordinal     not in range(128)</Message><Frame><File>parsetable.py</File><Line>15</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14747283</PostId><Url>http://stackoverflow.com/questions/14747283</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)</Message><Frame><File>/base/data/home/apps/s~posttofacebook123456/1.365133296513228525/kay/app.py</File><Line>371</Line><Method>get_response</Method></Frame><Frame><File>/base/data/home/apps/s~posttofacebook123456/1.365133296513228525/myapp/views.py</File><Line>116</Line><Method>index</Method></Frame><Frame><File>/base/data/home/apps/s~posttofacebook123456/1.365133296513228525/myapp/facebook.py</File><Line>140</Line><Method>put_object</Method></Frame><Frame><File>/base/data/home/apps/s~posttofacebook123456/1.365133296513228525/myapp/facebook.py</File><Line>291</Line><Method>request</Method></Frame><Frame><File>/python27_runtime/python27_dist/lib/python2.7/urllib.py</File><Line>1289</Line><Method>urlencode</Method></Frame></Stack></Post><Post><PostId>14771969</PostId><Url>http://stackoverflow.com/questions/14771969</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 10: ordinal not in range(128)</Message><Frame><File>../code/userinfo_extraction_old.py</File><Line>167</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14790983</PostId><Url>http://stackoverflow.com/questions/14790983</Url><Stack><Type>UnicodeEncodeError</Type><Message>'UCS-2' codec can't encode character '\U0001f005'</Message><Frame><File>pyshell#3</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14821718</PostId><Url>http://stackoverflow.com/questions/14821718</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)</Message><Frame><File>unicodetest.py</File><Line>12</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14983473</PostId><Url>http://stackoverflow.com/questions/14983473</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x8b' in position 26: ordinal not in range(128)</Message><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/gunicorn/workers/sync.py</File><Line>102</Line><Method>handle_request</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/contrib/staticfiles/handlers.py</File><Line>67</Line><Method>__call__</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/core/handlers/wsgi.py</File><Line>247</Line><Method>__call__</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/core/handlers/base.py</File><Line>188</Line><Method>get_response</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/middleware/gzip.py</File><Line>16</Line><Method>process_response</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/http/__init__.py</File><Line>699</Line><Method>_get_content</Method></Frame></Stack></Post><Post><PostId>14983473</PostId><Url>http://stackoverflow.com/questions/14983473</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x8b' in position 26: ordinal not in range(128)</Message><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/gunicorn/workers/sync.py</File><Line>102</Line><Method>handle_request</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/contrib/staticfiles/handlers.py</File><Line>67</Line><Method>__call__</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/core/handlers/wsgi.py</File><Line>247</Line><Method>__call__</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/core/handlers/base.py</File><Line>188</Line><Method>get_response</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/middleware/gzip.py</File><Line>16</Line><Method>process_response</Method></Frame><Frame><File>/home/toursprung/.virtualenvs/myproject/lib/python2.6/site-packages/django/http/__init__.py</File><Line>699</Line><Method>_get_content</Method></Frame></Stack></Post><Post><PostId>15138649</PostId><Url>http://stackoverflow.com/questions/15138649</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u017d' in position 112: ordinal not in range(128)</Message><Frame><File>manage.py</File><Line>14</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py</File><Line>459</Line><Method>execute_manager</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py</File><Line>382</Line><Method>execute</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/base.py</File><Line>196</Line><Method>run_from_argv</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/base.py</File><Line>232</Line><Method>execute</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/commands/startapp.py</File><Line>25</Line><Method>handle</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/management/templates.py</File><Line>162</Line><Method>handle</Method></Frame></Stack></Post><Post><PostId>15420467</PostId><Url>http://stackoverflow.com/questions/15420467</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\U0001f3c0' in position 153: character maps to</Message><Frame><File>tweets.py</File><Line>34</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>15535538</PostId><Url>http://stackoverflow.com/questions/15535538</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 0-1: character   maps to</Message><Frame><File>C:\xx\src\main.py</File><Line>8</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>15622027</PostId><Url>http://stackoverflow.com/questions/15622027</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 3717: ordinal not in range(128)</Message><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>lxml.etree.pyx</File><Line>2992</Line><Method>lxml.etree.fromstring (src\lxml\lxml.etree.c:62311)</Method></Frame><Frame><File>parser.pxi</File><Line>1585</Line><Method>lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:91625)</Method></Frame><Frame><File>pyshell#3</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1301</Line><Method>XML</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1641</Line><Method>feed</Method></Frame></Stack></Post><Post><PostId>15622027</PostId><Url>http://stackoverflow.com/questions/15622027</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 3717: ordinal not in range(128)</Message><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>lxml.etree.pyx</File><Line>2992</Line><Method>lxml.etree.fromstring (src\lxml\lxml.etree.c:62311)</Method></Frame><Frame><File>parser.pxi</File><Line>1585</Line><Method>lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:91625)</Method></Frame><Frame><File>pyshell#3</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1301</Line><Method>XML</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1641</Line><Method>feed</Method></Frame></Stack></Post><Post><PostId>15719481</PostId><Url>http://stackoverflow.com/questions/15719481</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf3' in position 1: ordinal not in range(128)</Message><Frame><File>Z:\Coding\Baseball\fetch_rosters_yahoo.py</File><Line>213</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>15740847</PostId><Url>http://stackoverflow.com/questions/15740847</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)</Message><Frame><File>wrong.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>15814370</PostId><Url>http://stackoverflow.com/questions/15814370</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xdf' in position 12: ordinal not in range(128)</Message><Frame><File>C:\Python27\extract_osm_road_nw.py</File><Line>76</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>16034060</PostId><Url>http://stackoverflow.com/questions/16034060</Url><Stack><Type>UnicodeEncodeError</Type><Message>'locale' codec can't encode character '\u5e74' in position 2</Message><Frame><File>a.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>16250505</PostId><Url>http://stackoverflow.com/questions/16250505</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb7' in position 61: ordinal not   in range(128)</Message><Frame><File>parser.py</File><Line>114</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>16268602</PostId><Url>http://stackoverflow.com/questions/16268602</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)</Message><Frame><File>so.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/python_twitter-0.8.7-py2.7.egg/twitter.py</File><Line>2419</Line><Method>GetSearch</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/python_twitter-0.8.7-py2.7.egg/twitter.py</File><Line>4041</Line><Method>_FetchUrl</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2-1.5.211-py2.7.egg/oauth2/__init__.py</File><Line>440</Line><Method>to_url</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py</File><Line>1337</Line><Method>urlencode</Method></Frame></Stack></Post><Post><PostId>16491789</PostId><Url>http://stackoverflow.com/questions/16491789</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 13-63: character maps to</Message><Frame><File>F:\ProgrammingPoint\workspace-new\PyTest\tweet_sentiment.py</File><Line>41</Line><Method>module</Method></Frame><Frame><File>F:\ProgrammingPoint\workspace-new\PyTest\tweet_sentiment.py</File><Line>36</Line><Method>main</Method></Frame><Frame><File>F:\ProgrammingPoint\workspace-new\PyTest\tweet_sentiment.py</File><Line>23</Line><Method>hw</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp1252.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>16536687</PostId><Url>http://stackoverflow.com/questions/16536687</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 34-35: ordinal not in range(128)</Message><Frame><File>/home/admin/data/virtualenvs/myapp/project/manage.py</File><Line>28</Line><Method>module</Method></Frame><Frame><File>/home/admin/data/virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py</File><Line>443</Line><Method>execute_from_command_line</Method></Frame><Frame><File>/home/admin/data/virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py</File><Line>382</Line><Method>execute</Method></Frame><Frame><File>/home/admin/data/virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/management/base.py</File><Line>196</Line><Method>run_from_argv</Method></Frame><Frame><File>/home/admin/data/virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/management/base.py</File><Line>232</Line><Method>execute</Method></Frame><Frame><File>/home/admin/data/virtualenvs/myapp/project/helper/management/commands/1c-import.py</File><Line>94</Line><Method>handle</Method></Frame></Stack></Post><Post><PostId>16624424</PostId><Url>http://stackoverflow.com/questions/16624424</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 73-79: ordinal not in range(128)</Message><Frame><File>pyshell#19</File><Line>1</Line><Method>module</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>156</Line><Method>urlopen</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>469</Line><Method>open</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>487</Line><Method>_open</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>447</Line><Method>_call_chain</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>1283</Line><Method>https_open</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py</File><Line>1248</Line><Method>do_open</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py</File><Line>1061</Line><Method>request</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py</File><Line>1089</Line><Method>_send_request</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py</File><Line>953</Line><Method>putrequest</Method></Frame></Stack></Post><Post><PostId>16680970</PostId><Url>http://stackoverflow.com/questions/16680970</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 4586-4611: ordinal not in range(128)</Message><Frame><File>/usr/local/uploader/upload_data.py</File><Line>179</Line><Method>module</Method></Frame><Frame><File>/usr/local/uploader/upload_data.py</File><Line>170</Line><Method>main</Method></Frame><Frame><File>/usr/local/uploader/upload_data.py</File><Line>100</Line><Method>upload</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/oauth2client/util.py</File><Line>128</Line><Method>positional_wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/oauth2client/client.py</File><Line>490</Line><Method>new_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/httplib2/__init__.py</File><Line>1570</Line><Method>request</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/httplib2/__init__.py</File><Line>1317</Line><Method>_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/site-packages/httplib2/__init__.py</File><Line>1253</Line><Method>_conn_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/httplib.py</File><Line>973</Line><Method>request</Method></Frame><Frame><File>/usr/local/lib/python2.7/httplib.py</File><Line>1007</Line><Method>_send_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/httplib.py</File><Line>969</Line><Method>endheaders</Method></Frame><Frame><File>/usr/local/lib/python2.7/httplib.py</File><Line>833</Line><Method>_send_output</Method></Frame><Frame><File>/usr/local/lib/python2.7/httplib.py</File><Line>805</Line><Method>send</Method></Frame><Frame><File>/usr/local/lib/python2.7/ssl.py</File><Line>229</Line><Method>sendall</Method></Frame><Frame><File>/usr/local/lib/python2.7/ssl.py</File><Line>198</Line><Method>send</Method></Frame></Stack></Post><Post><PostId>16696737</PostId><Url>http://stackoverflow.com/questions/16696737</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 94-95: ordinal not in range(128)</Message><Frame><File>./manage.py</File><Line>10</Line><Method>module</Method></Frame><Frame><File>/home/tomus/dev/bsk/venv/lib/python2.7/site-    packages/django/core/management/__init__.py</File><Line>453</Line><Method>execute_from_command_line</Method></Frame><Frame><File>/home/tomus/dev/bsk/venv/lib/python2.7/site-packages/django/core/management/__init__.py</File><Line>392</Line><Method>execute</Method></Frame><Frame><File>/home/tomus/dev/bsk/venv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>229</Line><Method>run_from_argv</Method></Frame></Stack></Post><Post><PostId>17059283</PostId><Url>http://stackoverflow.com/questions/17059283</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)</Message><Frame><File>F:\EZHUTHANI_WIN\ezhuthani\beditor.py</File><Line>498</Line><Method>PreviewConv</Method></Frame><Frame><File>C:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>17430168</PostId><Url>http://stackoverflow.com/questions/17430168</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe5' in position 1: ordinal not in range(128)</Message><Frame><File>testu.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17665213</PostId><Url>http://stackoverflow.com/questions/17665213</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xb0' in position 1: ordinal not in range(128)</Message><Frame><File>play.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python2.7/json/__init__.py</File><Line>190</Line><Method>dump</Method></Frame></Stack></Post><Post><PostId>17825570</PostId><Url>http://stackoverflow.com/questions/17825570</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 33-36: ordinal not in range(128)</Message><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>739</Line><Method>module</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>705</Line><Method>run</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>77</Line><Method>BuildAction</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>359</Line><Method>BuildApplication</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/__init__.py</File><Line>628</Line><Method>App</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/lib/scons/engine/SCons/Environment.py</File><Line>223</Line><Method>__call__</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>997</Line><Method>BuildApp</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>632</Line><Method>BuildLibrary</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/headermap.py</File><Line>194</Line><Method>dump</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>739</Line><Method>module</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>705</Line><Method>run</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>77</Line><Method>BuildAction</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>359</Line><Method>BuildApplication</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/__init__.py</File><Line>628</Line><Method>App</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/lib/scons/engine/SCons/Environment.py</File><Line>223</Line><Method>__call__</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>997</Line><Method>BuildApp</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>632</Line><Method>BuildLibrary</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/headermap.py</File><Line>194</Line><Method>dump</Method></Frame></Stack></Post><Post><PostId>17825570</PostId><Url>http://stackoverflow.com/questions/17825570</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 33-36: ordinal not in range(128)</Message><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>739</Line><Method>module</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>705</Line><Method>run</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>77</Line><Method>BuildAction</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>359</Line><Method>BuildApplication</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/__init__.py</File><Line>628</Line><Method>App</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/lib/scons/engine/SCons/Environment.py</File><Line>223</Line><Method>__call__</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>997</Line><Method>BuildApp</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>632</Line><Method>BuildLibrary</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/headermap.py</File><Line>194</Line><Method>dump</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>739</Line><Method>module</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>705</Line><Method>run</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/bin/apportable</File><Line>77</Line><Method>BuildAction</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>359</Line><Method>BuildApplication</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/__init__.py</File><Line>628</Line><Method>App</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/lib/scons/engine/SCons/Environment.py</File><Line>223</Line><Method>__call__</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>997</Line><Method>BuildApp</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/site_init.py</File><Line>632</Line><Method>BuildLibrary</Method></Frame><Frame><File>/Users/apple/.apportable/SDK/site_scons/build/headermap.py</File><Line>194</Line><Method>dump</Method></Frame></Stack></Post><Post><PostId>17868974</PostId><Url>http://stackoverflow.com/questions/17868974</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2022' in position 697: ordinal not in range(128)</Message><Frame><File>./setup.py</File><Line>191</Line><Method>module</Method></Frame><Frame><File>./setup.py</File><Line>185</Line><Method>_setup</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/core.py</File><Line>151</Line><Method>setup</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>986</Line><Method>run_commands</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>1006</Line><Method>run_command</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/test.py</File><Line>111</Line><Method>run</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/dist.py</File><Line>284</Line><Method>fetch_build_eggs</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/pkg_resources.py</File><Line>573</Line><Method>resolve</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/pkg_resources.py</File><Line>823</Line><Method>best_match</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/pkg_resources.py</File><Line>835</Line><Method>obtain</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/dist.py</File><Line>327</Line><Method>fetch_build_egg</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/easy_install.py</File><Line>453</Line><Method>easy_install</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/easy_install.py</File><Line>483</Line><Method>install_item</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/easy_install.py</File><Line>663</Line><Method>install_eggs</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/easy_install.py</File><Line>938</Line><Method>build_and_install</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/easy_install.py</File><Line>927</Line><Method>run_setup</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/sandbox.py</File><Line>62</Line><Method>run_setup</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/sandbox.py</File><Line>105</Line><Method>run</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/sandbox.py</File><Line>64</Line><Method>lambda</Method></Frame><Frame><File>setup.py</File><Line>117</Line><Method>module</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/core.py</File><Line>151</Line><Method>setup</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>986</Line><Method>run_commands</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>1006</Line><Method>run_command</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/bdist_egg.py</File><Line>167</Line><Method>run</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/cmd.py</File><Line>333</Line><Method>run_command</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>1006</Line><Method>run_command</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/egg_info.py</File><Line>170</Line><Method>run</Method></Frame><Frame><File>/Users/Andrew/Documents/Academic Work/Computing/Extracurricular Programming/zfec-1.4.24/setuptools-0.6c16dev3.egg/setuptools/command/egg_info.py</File><Line>379</Line><Method>write_pkg_info</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>1088</Line><Method>write_pkg_info</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/distutils/dist.py</File><Line>1113</Line><Method>write_pkg_file</Method></Frame></Stack></Post><Post><PostId>17870913</PostId><Url>http://stackoverflow.com/questions/17870913</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xff' in position 1:</Message><Frame><File>audio2.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17918746</PostId><Url>http://stackoverflow.com/questions/17918746</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u7535' in position 0: ordinal not in range(128)</Message><Frame><File>D:\Temp\windows_prn_utf8.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18054337</PostId><Url>http://stackoverflow.com/questions/18054337</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 77-82: ordinal not in range(128)</Message><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py</File><Line>570</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~app/dev.369284735686497536/imapapi.py</File><Line>269</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/s~app/dev.369284735686497536/utils/imap.py</File><Line>123</Line><Method>search_message</Method></Frame><Frame><File>/base/data/home/apps/s~app/dev.369284735686497536/imapclient/imapclient.py</File><Line>569</Line><Method>search</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>625</Line><Method>search</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>1070</Line><Method>_simple_command</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>857</Line><Method>_command</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>1178</Line><Method>send</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/ssl.py</File><Line>232</Line><Method>write</Method></Frame></Stack></Post><Post><PostId>18113547</PostId><Url>http://stackoverflow.com/questions/18113547</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u0142' in position 2: ordinal not in range(128)</Message><Frame><File>MethodTest.py</File><Line>11</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18266581</PostId><Url>http://stackoverflow.com/questions/18266581</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 95859-95860: ordinal not in range(128)</Message><Frame><File>/local/mnt/workspace/user/Automation/RunCheckOnOpenGerrits_BT.py</File><Line>416</Line><Method>module</Method></Frame><Frame><File>/local/mnt/workspace/user/Automation/RunCheckOnOpenGerrits_BT.py</File><Line>37</Line><Method>email</Method></Frame><Frame><File>/usr/lib/python2.7/email/mime/text.py</File><Line>30</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/email/message.py</File><Line>226</Line><Method>set_payload</Method></Frame><Frame><File>/usr/lib/python2.7/email/message.py</File><Line>262</Line><Method>set_charset</Method></Frame></Stack></Post><Post><PostId>18303091</PostId><Url>http://stackoverflow.com/questions/18303091</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)</Message><Frame><File>example.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18404546</PostId><Url>http://stackoverflow.com/questions/18404546</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 0-1: character maps to</Message><Frame><File>cjk.py</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>18471198</PostId><Url>http://stackoverflow.com/questions/18471198</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py</File><Line>140</Line><Method>get_response</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/response.py</File><Line>105</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/response.py</File><Line>82</Line><Method>rendered_content</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>140</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>124</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>124</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>134</Line><Method>_render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py</File><Line>284</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py</File><Line>63</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py</File><Line>284</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>830</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>74</Line><Method>render_node</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/debug.py</File><Line>84</Line><Method>render</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/base.py</File><Line>606</Line><Method>resolve</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/template/defaultfilters.py</File><Line>41</Line><Method>_dec</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py</File><Line>107</Line><Method>force_text</Method></Frame></Stack></Post><Post><PostId>18486287</PostId><Url>http://stackoverflow.com/questions/18486287</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)</Message><Frame><File>scripts/script.py</File><Line>33</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18572181</PostId><Url>http://stackoverflow.com/questions/18572181</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character '\xf6' in position 188: ordinal not in range(128)</Message><Frame><File>testing.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python3.2/smtplib.py</File><Line>812</Line><Method>send_message</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>91</Line><Method>flatten</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>137</Line><Method>_write</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>163</Line><Method>_dispatch</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>398</Line><Method>_handle_text</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>201</Line><Method>_handle_text</Method></Frame><Frame><File>/usr/lib/python3.2/email/generator.py</File><Line>357</Line><Method>write</Method></Frame></Stack></Post><Post><PostId>18841324</PostId><Url>http://stackoverflow.com/questions/18841324</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2019' in position 7: ordinal not in range(128)</Message><Frame><File>load.py</File><Line>165</Line><Method>module</Method></Frame><Frame><File>load.py</File><Line>17</Line><Method>main</Method></Frame><Frame><File>load.py</File><Line>157</Line><Method>beers</Method></Frame><Frame><File>load.py</File><Line>64</Line><Method>send_post</Method></Frame><Frame><File>load.py</File><Line>49</Line><Method>encode_multipart_data</Method></Frame><Frame><File>load.py</File><Line>34</Line><Method>encode_field</Method></Frame><Frame><File>/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py</File><Line>53</Line><Method>b64encode</Method></Frame></Stack></Post><Post><PostId>18940810</PostId><Url>http://stackoverflow.com/questions/18940810</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa1' in position 0: ordinal not in range(128)</Message><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site packages/tornado/websocket.py</File><Line>303</Line><Method>wrapper</Method></Frame><Frame><File>test.py</File><Line>11</Line><Method>on_message</Method></Frame></Stack></Post><Post><PostId>19145183</PostId><Url>http://stackoverflow.com/questions/19145183</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2026' in position 139: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/iostream.py</File><Line>341</Line><Method>wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>203</Line><Method>parse_json</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>226</Line><Method>parse_response</Method></Frame><Frame><File>fetch_script.py</File><Line>57</Line><Method>callback</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py</File><Line>458</Line><Method>_run_callback</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/iostream.py</File><Line>341</Line><Method>wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>203</Line><Method>parse_json</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>226</Line><Method>parse_response</Method></Frame><Frame><File>fetch_script.py</File><Line>57</Line><Method>callback</Method></Frame></Stack></Post><Post><PostId>19145183</PostId><Url>http://stackoverflow.com/questions/19145183</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2026' in position 139: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/iostream.py</File><Line>341</Line><Method>wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>203</Line><Method>parse_json</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>226</Line><Method>parse_response</Method></Frame><Frame><File>fetch_script.py</File><Line>57</Line><Method>callback</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py</File><Line>458</Line><Method>_run_callback</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/iostream.py</File><Line>341</Line><Method>wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>331</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py</File><Line>302</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>203</Line><Method>parse_json</Method></Frame><Frame><File>/usr/local/streaming/twitter-stream.py</File><Line>226</Line><Method>parse_response</Method></Frame><Frame><File>fetch_script.py</File><Line>57</Line><Method>callback</Method></Frame></Stack></Post><Post><PostId>19146524</PostId><Url>http://stackoverflow.com/questions/19146524</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x82' in position 0: ordinal not in range(128)</Message><Frame><File>fix.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19168043</PostId><Url>http://stackoverflow.com/questions/19168043</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 106: ordinal not in range(128)</Message><Frame><File>./flattenXml.py</File><Line>135</Line><Method>module</Method></Frame><Frame><File>./flattenXml.py</File><Line>116</Line><Method>process</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>104</Line><Method>linearize</Method></Frame><Frame><File>./flattenXml.py</File><Line>83</Line><Method>linearize</Method></Frame></Stack></Post><Post><PostId>19194348</PostId><Url>http://stackoverflow.com/questions/19194348</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe1' in position 2: ordinal not in range(128)</Message><Frame><File>D:\Python27\lib\site-packages\django\core\handlers\base.py</File><Line>115</Line><Method>get_response</Method></Frame><Frame><File>D:\Project\Reservation\Translator\views.py</File><Line>72</Line><Method>getParams</Method></Frame><Frame><File>D:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame><Frame><File>D:\Python27\lib\site-packages\django\core\handlers\base.py</File><Line>115</Line><Method>get_response</Method></Frame><Frame><File>D:\Project\Reservation\Translator\views.py</File><Line>72</Line><Method>getParams</Method></Frame><Frame><File>D:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>19194348</PostId><Url>http://stackoverflow.com/questions/19194348</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe1' in position 2: ordinal not in range(128)</Message><Frame><File>D:\Python27\lib\site-packages\django\core\handlers\base.py</File><Line>115</Line><Method>get_response</Method></Frame><Frame><File>D:\Project\Reservation\Translator\views.py</File><Line>72</Line><Method>getParams</Method></Frame><Frame><File>D:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame><Frame><File>D:\Python27\lib\site-packages\django\core\handlers\base.py</File><Line>115</Line><Method>get_response</Method></Frame><Frame><File>D:\Project\Reservation\Translator\views.py</File><Line>72</Line><Method>getParams</Method></Frame><Frame><File>D:\Python27\lib\encodings\utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>19211327</PostId><Url>http://stackoverflow.com/questions/19211327</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 24-25: character maps to</Message><Frame><File>C:\test.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>19273624</PostId><Url>http://stackoverflow.com/questions/19273624</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\x80' in position 4: character maps to</Message><Frame><File>C:\Python27\test1.py</File><Line>7</Line><Method>module</Method></Frame><Frame><File>C:\Python27\test1.py</File><Line>5</Line><Method>foo</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp850.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>19284130</PostId><Url>http://stackoverflow.com/questions/19284130</Url><Stack><Type>UnicodeEncodeError</Type><Message>'utf-8' codec can't encode character '\udcb4' in position 4: surrogates not allowed</Message><Frame><File>unicode.py</File><Line>157</Line><Method>module</Method></Frame><Frame><File>unicode.py</File><Line>42</Line><Method>test0</Method></Frame></Stack></Post><Post><PostId>19653131</PostId><Url>http://stackoverflow.com/questions/19653131</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)</Message><Frame><File>pyshell#9</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19696652</PostId><Url>http://stackoverflow.com/questions/19696652</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>ddd.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19696652</PostId><Url>http://stackoverflow.com/questions/19696652</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>ddd.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19740385</PostId><Url>http://stackoverflow.com/questions/19740385</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u201c' in position 215: ordinal not in range(128)</Message><Frame><File>C:\DebSeal\IUB MS Program\IUB Sem III\Facebook Kaggle Comp\Src\facebookChallenge.py</File><Line>62</Line><Method>module</Method></Frame><Frame><File>C:\DebSeal\IUB MS Program\IUB Sem III\Facebook Kaggle Comp\Src\facebookChallenge.py</File><Line>42</Line><Method>computeTFIDF</Method></Frame><Frame><File>C:\Python27\lib\csv.py</File><Line>104</Line><Method>next</Method></Frame></Stack></Post><Post><PostId>19755907</PostId><Url>http://stackoverflow.com/questions/19755907</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 10-13: character maps to</Message><Frame><File>C:\Python\xxx.py</File><Line>45</Line><Method>OnCopyData</Method></Frame><Frame><File>C:\Python\python-3.3.2\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>19806219</PostId><Url>http://stackoverflow.com/questions/19806219</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)</Message><Frame><File>/home/cooper/Document/20131106.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.3-py2.7-linux-i686.egg/MySQLdb/cursors.py</File><Line>224</Line><Method>executemany</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.3-py2.7-linux-i686.egg/MySQLdb/cursors.py</File><Line>92</Line><Method>_warning_check</Method></Frame><Frame><File>/usr/lib/python2.7/warnings.py</File><Line>29</Line><Method>_show_warning</Method></Frame><Frame><File>/usr/lib/python2.7/warnings.py</File><Line>38</Line><Method>formatwarning</Method></Frame></Stack></Post><Post><PostId>19935989</PostId><Url>http://stackoverflow.com/questions/19935989</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xbb' in position 98: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.7/threading.py</File><Line>530</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>/usr/local/lib/python2.7/threading.py</File><Line>483</Line><Method>run</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/testing/mozbase/mozprocess/mozprocess/processhandler.py</File><Line>698</Line><Method>_processOutput</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/testing/mozbase/mozprocess/mozprocess/processhandler.py</File><Line>663</Line><Method>processOutputLine</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/python/mach/mach/mixin/process.py</File><Line>86</Line><Method>handleLine</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/python/mozbuild/mozbuild/mach_commands.py</File><Line>242</Line><Method>on_line</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/python/mach/mach/mixin/logging.py</File><Line>54</Line><Method>log</Method></Frame><Frame><File>/usr/local/lib/python2.7/logging/__init__.py</File><Line>1191</Line><Method>log</Method></Frame><Frame><File>/usr/local/lib/python2.7/logging/__init__.py</File><Line>1246</Line><Method>_log</Method></Frame><Frame><File>/usr/local/lib/python2.7/logging/__init__.py</File><Line>1256</Line><Method>handle</Method></Frame><Frame><File>/usr/local/lib/python2.7/logging/__init__.py</File><Line>1293</Line><Method>callHandlers</Method></Frame><Frame><File>/usr/local/lib/python2.7/logging/__init__.py</File><Line>740</Line><Method>handle</Method></Frame><Frame><File>/home/ternes3/Downloads/mozilla-release/python/mozbuild/mozbuild/mach_commands.py</File><Line>75</Line><Method>emit</Method></Frame></Stack></Post><Post><PostId>19963796</PostId><Url>http://stackoverflow.com/questions/19963796</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\ufffd' in position 104: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/flask/app.py</File><Line>1687</Line><Method>wsgi_app</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/flask/app.py</File><Line>1360</Line><Method>full_dispatch_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/flask/app.py</File><Line>1358</Line><Method>full_dispatch_request</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/flask/app.py</File><Line>1344</Line><Method>dispatch_request</Method></Frame><Frame><File>./app/globals.py</File><Line>94</Line><Method>decorator</Method></Frame><Frame><File>./app/views.py</File><Line>607</Line><Method>paypal_webhook</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>127</Line><Method>urlopen</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>401</Line><Method>open</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>419</Line><Method>_open</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>379</Line><Method>_call_chain</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>1219</Line><Method>https_open</Method></Frame><Frame><File>/usr/lib/python2.7/urllib2.py</File><Line>1178</Line><Method>do_open</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>962</Line><Method>request</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>996</Line><Method>_send_request</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>958</Line><Method>endheaders</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>822</Line><Method>_send_output</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>794</Line><Method>send</Method></Frame><Frame><File>/usr/lib/python2.7/ssl.py</File><Line>229</Line><Method>sendall</Method></Frame><Frame><File>/usr/lib/python2.7/ssl.py</File><Line>198</Line><Method>send</Method></Frame></Stack></Post><Post><PostId>20164611</PostId><Url>http://stackoverflow.com/questions/20164611</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\ufeff' in position 0: character maps to</Message><Frame><File>C:\Python33\final.py</File><Line>15</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1250.py</File><Line>23</Line><Method>decode</Method></Frame><Frame><File>C:\Python33\final.py</File><Line>22</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1250.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>20164611</PostId><Url>http://stackoverflow.com/questions/20164611</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\ufeff' in position 0: character maps to</Message><Frame><File>C:\Python33\final.py</File><Line>15</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1250.py</File><Line>23</Line><Method>decode</Method></Frame><Frame><File>C:\Python33\final.py</File><Line>22</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1250.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>20228830</PostId><Url>http://stackoverflow.com/questions/20228830</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 5: ordinal not in range(128)</Message><Frame><File>myscript.py</File><Line>48</Line><Method>module</Method></Frame><Frame><File>myscript.py</File><Line>38</Line><Method>add_categories_to_db</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>545</Line><Method>save</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>573</Line><Method>save_base</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>654</Line><Method>_save_table</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>687</Line><Method>_do_insert</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py</File><Line>232</Line><Method>_insert</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/query.py</File><Line>1511</Line><Method>insert_query</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py</File><Line>898</Line><Method>execute_sql</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py</File><Line>69</Line><Method>execute</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py</File><Line>53</Line><Method>execute</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py</File><Line>124</Line><Method>execute</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py</File><Line>159</Line><Method>execute</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/MySQLdb/connections.py</File><Line>264</Line><Method>literal</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/MySQLdb/connections.py</File><Line>197</Line><Method>string_literal</Method></Frame></Stack></Post><Post><PostId>20329896</PostId><Url>http://stackoverflow.com/questions/20329896</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character u'\u2013' in position</Message><Frame><File>C:\Python27\utf8.py</File><Line>3</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp775.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>20448062</PostId><Url>http://stackoverflow.com/questions/20448062</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)</Message><Frame><File>C:\Users\GAMER\Desktop\Padai\Fall 13\ADB\player_extract.py</File><Line>49</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>20492324</PostId><Url>http://stackoverflow.com/questions/20492324</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 45-46: ordinal not in range(128)</Message><Frame><File>/home/bigb/Programming/google_appengine/google/appengine/runtime/wsgi.py</File><Line>266</Line><Method>Handle</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>1519</Line><Method>__call__</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>1511</Line><Method>__call__</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>1505</Line><Method>__call__</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>1253</Line><Method>default_dispatcher</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>1077</Line><Method>__call__</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>547</Line><Method>dispatch</Method></Frame><Frame><File>/home/bigb/Programming/google_appengine/lib/webapp2-2.3/webapp2.py</File><Line>545</Line><Method>dispatch</Method></Frame><Frame><File>/home/bigb/Programming/Blog/my-ramblings/blog.py</File><Line>232</Line><Method>post</Method></Frame><Frame><File>/home/bigb/Programming/Blog/my-ramblings/blog.py</File><Line>43</Line><Method>markDown</Method></Frame><Frame><File>/usr/lib/python2.7/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>20603810</PostId><Url>http://stackoverflow.com/questions/20603810</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa0' in position 60: ordinal not in range(128)</Message><Frame><File>my_test_bot.py</File><Line>11</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>20637734</PostId><Url>http://stackoverflow.com/questions/20637734</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 7: ordinal not in range(128)</Message><Frame><File>/home/frlan/.virtualenvs/gascylinders/local/lib/python2.7/site-packages/django/core/handlers/base.py</File><Line>114</Line><Method>get_response</Method></Frame><Frame><File>/home/frlan/.virtualenvs/gascylinders/local/lib/python2.7/site-packages/django/views/generic/base.py</File><Line>69</Line><Method>view</Method></Frame><Frame><File>/home/frlan/.virtualenvs/gascylinders/local/lib/python2.7/site-packages/django/views/generic/base.py</File><Line>87</Line><Method>dispatch</Method></Frame><Frame><File>/home/frlan/.virtualenvs/gascylinders/local/lib/python2.7/site-packages/django/views/generic/edit.py</File><Line>171</Line><Method>post</Method></Frame><Frame><File>/home/frlan/quellen/git/gascylinders-rt-frontend/gascylinders/rtfrontend/views.py</File><Line>12</Line><Method>form_valid</Method></Frame><Frame><File>/home/frlan/quellen/git/gascylinders-rt-frontend/gascylinders/rtfrontend/forms.py</File><Line>124</Line><Method>send_email</Method></Frame></Stack></Post><Post><PostId>20640021</PostId><Url>http://stackoverflow.com/questions/20640021</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u3030' in position 0: character maps to</Message><Frame><File>C:\Users\mastelj\workspace\stickies\stickies.py</File><Line>67</Line><Method>OnCopyData</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>20831894</PostId><Url>http://stackoverflow.com/questions/20831894</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u201c' in position</Message><Frame><File>scraper.py</File><Line>20</Line><Method>module</Method></Frame><Frame><File>F:\dev\own\pyscraper\venv\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>20884036</PostId><Url>http://stackoverflow.com/questions/20884036</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2013' in position</Message><Frame><File>C:\Program Files\Python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>21027726</PostId><Url>http://stackoverflow.com/questions/21027726</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2019' in position</Message><Frame><File>program.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp437.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>21087311</PostId><Url>http://stackoverflow.com/questions/21087311</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 20: ordinal not in range(128)</Message><Frame><File>/usr/local/lib/python2.6/SocketServer.py</File><Line>535</Line><Method>process_request</Method></Frame><Frame><File>/usr/local/lib/python2.6/SocketServer.py</File><Line>320</Line><Method>finish_request</Method></Frame><Frame><File>/usr/local/lib/python2.6/SocketServer.py</File><Line>615</Line><Method>__init__</Method></Frame><Frame><File>./papercut.py</File><Line>221</Line><Method>handle</Method></Frame><Frame><File>./papercut.py</File><Line>410</Line><Method>do_ARTICLE</Method></Frame><Frame><File>/usr/local/lib/python2.6/encodings/cp1250.py</File><Line>15</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>21111460</PostId><Url>http://stackoverflow.com/questions/21111460</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2026' in position 0: character maps to</Message><Frame><File>main.py</File><Line>48</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp852.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>21116412</PostId><Url>http://stackoverflow.com/questions/21116412</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\x80' in position 5: character maps to</Message><Frame><File>D:\Study\Pedia\Python Book\6. Functions\2. Built-in functions\ord_chr.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>21218412</PostId><Url>http://stackoverflow.com/questions/21218412</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2013' in position 16: ordinal not in range(128)</Message><Frame><File>./r.py</File><Line>11</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21386165</PostId><Url>http://stackoverflow.com/questions/21386165</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2022' in position 226:   ordinal not in range(128)</Message><Frame><File>C:\Python27\demo_amazon.py</File><Line>14</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21475306</PostId><Url>http://stackoverflow.com/questions/21475306</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2590' in position 25: character maps to</Message><Frame><File>wheel.py</File><Line>107</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp852.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>21488574</PostId><Url>http://stackoverflow.com/questions/21488574</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2019' in position 5:     ordinal not in range(128)</Message><Frame><File>pyshell#285</File><Line>1</Line><Method>module</Method></Frame><Frame><File>D2soup1.py</File><Line>86</Line><Method>module</Method></Frame><Frame><File>D2soup1.py</File><Line>30</Line><Method>test</Method></Frame></Stack></Post><Post><PostId>21510996</PostId><Url>http://stackoverflow.com/questions/21510996</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2039' in position 4165: ordinal not in range(128)</Message><Frame><File>download.py</File><Line>23</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21634912</PostId><Url>http://stackoverflow.com/questions/21634912</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2026' in position 139: ordinal not in range(128)</Message><Frame><File>twitter_search_csv.py</File><Line>25</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21635034</PostId><Url>http://stackoverflow.com/questions/21635034</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21947415</PostId><Url>http://stackoverflow.com/questions/21947415</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 47:</Message><Frame><File>google-calendar-test.py</File><Line>8</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21971425</PostId><Url>http://stackoverflow.com/questions/21971425</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe4' in position 29: ordinal not in range(128)</Message><Frame><File>Clipfinder.py</File><Line>254</Line><Method>module</Method></Frame><Frame><File>Clipfinder.py</File><Line>205</Line><Method>copyProcess</Method></Frame></Stack></Post><Post><PostId>22184178</PostId><Url>http://stackoverflow.com/questions/22184178</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 8: ordinal not in range(128)</Message><Frame><File>SR2works4real2.py</File><Line>18</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python2.7/csv.py</File><Line>154</Line><Method>writerows</Method></Frame></Stack></Post><Post><PostId>22184501</PostId><Url>http://stackoverflow.com/questions/22184501</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2122' in position 0: ordinal not in range(128)</Message><Frame><File>pyshell#92</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>22187283</PostId><Url>http://stackoverflow.com/questions/22187283</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe7' in position 11: ordinal not in range(128)</Message><Frame><File>promoter.py</File><Line>325</Line><Method>process_unfollowbacks</Method></Frame><Frame><File>promoter.py</File><Line>618</Line><Method>add_user_to_database</Method></Frame></Stack></Post><Post><PostId>22442490</PostId><Url>http://stackoverflow.com/questions/22442490</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u0410' in position 0: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>22460240</PostId><Url>http://stackoverflow.com/questions/22460240</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe1' in position 16: ordinal not in range(128)</Message><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1836</Line><Method>__call__</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1820</Line><Method>wsgi_app</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1403</Line><Method>handle_exception</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1817</Line><Method>wsgi_app</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1477</Line><Method>full_dispatch_request</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1381</Line><Method>handle_user_exception</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/app.py</File><Line>1475</Line><Method>full_dispatch_request</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py</File><Line>125</Line><Method>dispatch_request</Method></Frame><Frame><File>/usr/lib/python2.7/cProfile.py</File><Line>149</Line><Method>runcall</Method></Frame><Frame><File>/home/numkem/src/sd/application/views/player.py</File><Line>54</Line><Method>player_show</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/templating.py</File><Line>128</Line><Method>render_template</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/flask/templating.py</File><Line>110</Line><Method>_render</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/jinja2/environment.py</File><Line>969</Line><Method>render</Method></Frame><Frame><File>/home/numkem/src/sd/venv/lib/python2.7/site-packages/jinja2/environment.py</File><Line>742</Line><Method>handle_exception</Method></Frame><Frame><File>/home/numkem/src/sd/application/templates/player/show.html</File><Line>1</Line><Method>top-level template code</Method></Frame><Frame><File>/home/numkem/src/sd/application/templates/base.html</File><Line>62</Line><Method>top-level template code</Method></Frame><Frame><File>/home/numkem/src/sd/application/templates/player/show.html</File><Line>27</Line><Method>block "body"</Method></Frame></Stack></Post><Post><PostId>22651764</PostId><Url>http://stackoverflow.com/questions/22651764</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xfc' in position 13: ordinal not in range(128)</Message><Frame><File>C:\Users\Jesus\Dropbox\coding\python\geocoder with uft-8, with complete output.py</File><Line>42</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>22664684</PostId><Url>http://stackoverflow.com/questions/22664684</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 45-50: ordinal not in range(128)</Message><Frame><File>debugger</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23160389</PostId><Url>http://stackoverflow.com/questions/23160389</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2014' in position 701: ordinal not in range(128)</Message><Frame><File>~My Documents\LiClipse Workspace\soup\soup.py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23276849</PostId><Url>http://stackoverflow.com/questions/23276849</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)</Message><Frame><File>C:\ZChenCode\unicode.py</File><Line>27</Line><Method>test_test1</Method></Frame><Frame><File>C:\Python27\ArcGIS10.3\Lib\unittest\case.py</File><Line>127</Line><Method>__exit__</Method></Frame></Stack></Post><Post><PostId>23333837</PostId><Url>http://stackoverflow.com/questions/23333837</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2192' in position 6238: character maps to</Message><Frame><File>C:\Users\Cayle J. Elsey\Dropbox\Programming\Salient_Point\networking.py</File><Line>10</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>23546589</PostId><Url>http://stackoverflow.com/questions/23546589</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xeb' in position 13559: ordinal not in range(128)</Message><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>C:\Users\Bart\Dropbox\Studie\2013-2014\BSc-KI\cite_parser\parser.py</File><Line>193</Line><Method>parse_references</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1126</Line><Method>tostring</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>820</Line><Method>write</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>C:\Users\Bart\Dropbox\Studie\2013-2014\BSc-KI\cite_parser\parser.py</File><Line>197</Line><Method>parse_references</Method></Frame></Stack></Post><Post><PostId>23546589</PostId><Url>http://stackoverflow.com/questions/23546589</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xeb' in position 13559: ordinal not in range(128)</Message><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>C:\Users\Bart\Dropbox\Studie\2013-2014\BSc-KI\cite_parser\parser.py</File><Line>193</Line><Method>parse_references</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>1126</Line><Method>tostring</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>820</Line><Method>write</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\xml\etree\ElementTree.py</File><Line>939</Line><Method>_serialize_xml</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>C:\Users\Bart\Dropbox\Studie\2013-2014\BSc-KI\cite_parser\parser.py</File><Line>197</Line><Method>parse_references</Method></Frame></Stack></Post><Post><PostId>23551434</PostId><Url>http://stackoverflow.com/questions/23551434</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 0-39: character maps to</Message><Frame><File>C:\Python34\rule90.py</File><Line>15</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>23825149</PostId><Url>http://stackoverflow.com/questions/23825149</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128)</Message><Frame><File>./parse_xml.py</File><Line>41</Line><Method>module</Method></Frame><Frame><File>./parse_xml.py</File><Line>29</Line><Method>parse_xml</Method></Frame></Stack></Post><Post><PostId>24001643</PostId><Url>http://stackoverflow.com/questions/24001643</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)</Message><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>string</File><Line>2</Line><Method>read_pajek</Method></Frame><Frame><File>C:\Python27\lib\site-packages\networkx\utils\decorators.py</File><Line>263</Line><Method>_open_file</Method></Frame><Frame><File>C:\Python27\lib\site-packages\networkx\readwrite\pajek.py</File><Line>134</Line><Method>read_pajek</Method></Frame><Frame><File>C:\Python27\lib\site-packages\networkx\readwrite\pajek.py</File><Line>170</Line><Method>parse_pajek</Method></Frame></Stack></Post><Post><PostId>24282195</PostId><Url>http://stackoverflow.com/questions/24282195</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xf3' in position 0: ordinal not in range(128)</Message><Frame><File>checker.py</File><Line>258</Line><Method>module</Method></Frame><Frame><File>checker.py</File><Line>243</Line><Method>process_file</Method></Frame><Frame><File>checker.py</File><Line>89</Line><Method>do_underline</Method></Frame><Frame><File>/usr/lib/python2.7/encodings/utf_8.py</File><Line>16</Line><Method>decode</Method></Frame></Stack></Post><Post><PostId>24307158</PostId><Url>http://stackoverflow.com/questions/24307158</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 68-74: ordinal not in range(128)</Message><Frame><File>read_subjects.py</File><Line>8</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24342517</PostId><Url>http://stackoverflow.com/questions/24342517</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 26041-26</Message><Frame><File>test.py</File><Line>12</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp1252.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>24387157</PostId><Url>http://stackoverflow.com/questions/24387157</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2211' in position 0: ordinal not in range(128)</Message><Frame><File>.\testXLRD.py</File><Line>21</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24470194</PostId><Url>http://stackoverflow.com/questions/24470194</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)</Message><Frame><File>test.py</File><Line>104</Line><Method>module</Method></Frame><Frame><File>test.py</File><Line>99</Line><Method>main</Method></Frame></Stack></Post><Post><PostId>24589586</PostId><Url>http://stackoverflow.com/questions/24589586</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u0412' in position 0: ordinal not in range(128)</Message><Frame><File>/PythonProject/1.py</File><Line>38</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24623134</PostId><Url>http://stackoverflow.com/questions/24623134</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)</Message><Frame><File>app.py</File><Line>34</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24674987</PostId><Url>http://stackoverflow.com/questions/24674987</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xbb' in position 8532: ordinal not in range(128)</Message><Frame><File>prettyhtmlfiles.py</File><Line>16</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24679587</PostId><Url>http://stackoverflow.com/questions/24679587</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2019' in position</Message><Frame><File>BUS.py</File><Line>30</Line><Method>module</Method></Frame><Frame><File>BUS.py</File><Line>29</Line><Method>main</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>24754861</PostId><Url>http://stackoverflow.com/questions/24754861</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u20ac' in position</Message><Frame><File>krneki.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp852.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>24776654</PostId><Url>http://stackoverflow.com/questions/24776654</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u2019' in position 89: character maps to</Message><Frame><File>E:\Python\RBTrends\RBTrendsAnalysis.py</File><Line>52</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>24801137</PostId><Url>http://stackoverflow.com/questions/24801137</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 0-12: character</Message><Frame><File>TestJsonLoadsStackOverflow.py</File><Line>23</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp437.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>24984110</PostId><Url>http://stackoverflow.com/questions/24984110</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u20ac' in position   2941: character maps to</Message><Frame><File>test.py</File><Line>68</Line><Method>module</Method></Frame><Frame><File>test.py</File><Line>39</Line><Method>url</Method></Frame><Frame><File>C:\Python33\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>25127935</PostId><Url>http://stackoverflow.com/questions/25127935</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode character '\u201c' in position</Message><Frame><File>json_test.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>json_test.py</File><Line>7</Line><Method>parse</Method></Frame><Frame><File>C:\Python34\lib\encodings\cp850.py</File><Line>19</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>25133626</PostId><Url>http://stackoverflow.com/questions/25133626</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 16-17: ordinal not in range(128)</Message><Frame><File>t3.py</File><Line>43</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>25250857</PostId><Url>http://stackoverflow.com/questions/25250857</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2019' in position 8: ordinal not in range(128)</Message><Frame><File>pyshell#10</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>25299040</PostId><Url>http://stackoverflow.com/questions/25299040</Url><Stack><Type>UnicodeEncodeError</Type><Message>'charmap' codec can't encode characters in position 2607-2613: character maps to</Message><Frame><File>C:\Python27\lib\site-packages\werkzeug\serving.py</File><Line>177</Line><Method>run_wsgi</Method></Frame><Frame><File>C:\Python27\lib\site-packages\werkzeug\serving.py</File><Line>167</Line><Method>execute</Method></Frame><Frame><File>C:\Python27\lib\site-packages\werkzeug\debug\__init__.py</File><Line>124</Line><Method>debug_application</Method></Frame><Frame><File>C:\Python27\lib\site-packages\werkzeug\debug\tbtools.py</File><Line>273</Line><Method>log</Method></Frame><Frame><File>C:\Python27\lib\encodings\cp866.py</File><Line>12</Line><Method>encode</Method></Frame></Stack></Post><Post><PostId>25386124</PostId><Url>http://stackoverflow.com/questions/25386124</Url><Stack><Type>UnicodeEncodeError</Type><Message>'mbcs' codec can't encode characters in position 0--1: invalid character</Message><Frame><File>D:\src\scratch\TestPythonNet\TestPythonNet\PythonRuntime\Lib\site.py</File><Line>481</Line><Method>execsitecustomize</Method></Frame><Frame><File>D:\src\scratch\TestPythonNet\TestPythonNet\PythonRuntime\Lib\site.py</File><Line>497</Line><Method>execusercustomize</Method></Frame></Stack></Post><Post><PostId>25386124</PostId><Url>http://stackoverflow.com/questions/25386124</Url><Stack><Type>UnicodeEncodeError</Type><Message>'mbcs' codec can't encode characters in position 0--1: invalid character</Message><Frame><File>D:\src\scratch\TestPythonNet\TestPythonNet\PythonRuntime\Lib\site.py</File><Line>481</Line><Method>execsitecustomize</Method></Frame><Frame><File>D:\src\scratch\TestPythonNet\TestPythonNet\PythonRuntime\Lib\site.py</File><Line>497</Line><Method>execusercustomize</Method></Frame></Stack></Post><Post><PostId>25455162</PostId><Url>http://stackoverflow.com/questions/25455162</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\xa3' in position 42: ordinal not in range(128)</Message><Frame><File>C:\Users\matt\Desktop\reddit.py</File><Line>49</Line><Method>title= (str((submission.title)).encode('utf-8','replace'))</Method></Frame></Stack></Post><Post><PostId>25510800</PostId><Url>http://stackoverflow.com/questions/25510800</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\x96' in position 14: ordinal not in range(128)</Message><Frame><File>C:\_WORKSPACE\ReportsInventory\CustomReports\CustomReports.py</File><Line>38</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>25697459</PostId><Url>http://stackoverflow.com/questions/25697459</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)</Message><Frame><File>t1.py</File><Line>86</Line><Method>module</Method></Frame><Frame><File>t1.py</File><Line>34</Line><Method>write_results</Method></Frame><Frame><File>/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py</File><Line>154</Line><Method>writerows</Method></Frame></Stack></Post><Post><PostId>25778068</PostId><Url>http://stackoverflow.com/questions/25778068</Url><Stack><Type>UnicodeEncodeError</Type><Message>'ascii' codec can't encode character u'\u2019' in position 9580: ordinal not in range(128)</Message><Frame><File>/usr/share/nginx/mandrill/mandrill.py</File><Line>16</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python2.7/email/mime/text.py</File><Line>30</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/email/message.py</File><Line>226</Line><Method>set_payload</Method></Frame><Frame><File>/usr/lib/python2.7/email/message.py</File><Line>262</Line><Method>set_charset</Method></Frame></Stack></Post></Posts>